import VerifiedReserving

/-! Axiom audit: every theorem in the development must depend only on
`propext`, `Classical.choice`, `Quot.sound`. Run with
`lake env lean VerifiedReserving/Test/Axioms.lean`. -/

open VerifiedReserving

-- keep each audit line on one line so CI can grep it
set_option format.width 400

#print axioms fhat_eq_weighted_average
#print axioms T_eq_sum_weighted_F
#print axioms weighted_sq_dev
#print axioms weighted_sq_dev_at_fhat
#print axioms Chat_succ
#print axioms Chat_diag
#print axioms reserve_zero_of_oldest
#print axioms msep_eq_sum_mackTerm
#print axioms se2rec_eq_closed
#print axioms se2rec_eq_msep
#print axioms ultimate_eq_mul_cdf
#print axioms bfReserve_smul
#print axioms bfReserve_add
#print axioms bfUltimate_of_ultimate
#print axioms bfReserve_of_ultimate
#print axioms one_le_cdf
#print axioms bfReserve_nonneg
#print axioms bfReserve_le
#print axioms RandomTriangle.stronglyMeasurable_Srv
#print axioms condExp_fhatRv
#print axioms RandomTriangle.stronglyMeasurable_fhatRv
#print axioms condExp_fhatRv_mul
#print axioms integral_fhatRv_mul
#print axioms integral_fhatRv
#print axioms RandomTriangle.ChatRv_succ
#print axioms RandomTriangle.stronglyMeasurable_ChatRv
#print axioms condExp_C_succ
#print axioms condExp_C_of_Mack1
#print axioms condExp_ChatRv
#print axioms condExp_ultimate_eq
#print axioms RandomTriangle.trueCDR_apply
#print axioms condExp_trueCDR_eq_zero
#print axioms condExp_C_of_Mack1_at
#print axioms condExp_C_ultimate_of_Mack1
#print axioms trueCDR_eq
#print axioms obsCDR_eq_reserve_sub
#print axioms RandomTriangle.obsCDRRv_apply
#print axioms RandomTriangle.fhatRv_sub_eq
#print axioms RandomTriangle.sq_fhatRv_sub
#print axioms condExp_sq_fhatRv_sub
#print axioms weighted_sq_dev_eps
#print axioms RandomTriangle.sigma2Rv_eq
#print axioms condExp_wssRv
#print axioms condExp_sigma2Rv
#print axioms condExp_eps
#print axioms condExp_sq_C_succ
#print axioms condExp_sq_C_succ_tower
#print axioms procVar_eq_sum
#print axioms condVar_C_eq_procVar
#print axioms condExp_sq_sub_of_stronglyMeasurable
#print axioms condMsep_eq
#print axioms mackEstimation_eq_sum_relVar
#print axioms one_add_sum_le_prod_one_add
#print axioms remainder_nonneg
#print axioms remainder_two
#print axioms remainder_eq_zero_of_subsingleton_support
#print axioms prod_one_add_le_exp_sum
#print axioms mackEstimation_le_bbmwEstimation
#print axioms bbmwEstimation_sub_mackEstimation
#print axioms bbmwEstimation_eq_mackEstimation_of_one_factor
#print axioms bbmwEstimation_sub_mackEstimation_le
#print axioms mackEstimation_lt_bbmwEstimation_Cex
#print axioms exists_mackEstimation_lt_bbmwEstimation
#print axioms mackEstimation_eq_rowSum
#print axioms bbmwEstimation_eq_rowProd
#print axioms bbmwTotalEstimation_sub_mackTotalEstimation
#print axioms rowProd_sub_rowSum_nonneg
#print axioms mackTotalEstimation_le_bbmwTotalEstimation
#print axioms rohrMsep_eq_rohrProcess_add_rohrParameter
#print axioms rohrRelParam_eq_relVar
#print axioms rohrParameter_eq_mackEstimation
#print axioms Chat_eq_Chat_mul_prod
#print axioms rohrProcess_eq_mackProcess
#print axioms rohrMsep_eq_msep
#print axioms msep_div_ultimate_sq
#print axioms msep_eq_mackProcess_add_mackEstimation
#print axioms rohrMsep_eq_mackProcess_add_mackEstimation
#print axioms bbmwEstimation_sub_rohrParameter
#print axioms rohrParameter_le_bbmwEstimation
#print axioms rohrMsepTotal_eq_msepTotal
#print axioms integrable_sq_of_memLp
#print axioms condExp_sq_sub_condExp
#print axioms condExp_sq_finsetSum_of_cross
#print axioms condExp_sq_finsetSum_sub_of_stronglyMeasurable
#print axioms memLp_eps
#print axioms condExp_ultimate_of_Mack1
#print axioms condVar_ultimate_eq_procVar
#print axioms condMsepTotal_eq
#print axioms sum_procVar_le_condMsepTotal
#print axioms msep_eq_mackProcess_add_mackEstimation_of_lt
#print axioms msepTotal_eq_sum_mackProcess_add_mackTotalEstimation
#print axioms NontrivialModel.exists_nontrivial_mack_model
#print axioms NontrivialModel.fhat0_unbiased
#print axioms NontrivialModel.ultimate_unbiased
#print axioms NontrivialModel.var_fhat0
#print axioms NontrivialModel.sigma2_unbiased

#print axioms setIntegral_inter_of_indep
#print axioms condExp_sup_of_indep
#print axioms RandomTriangle.stronglyMeasurable_rowSigmaAll
#print axioms RandomTriangle.stronglyMeasurable_rowSigma
#print axioms indep_rowSigmaAll_otherRowsAll
#print axioms indep_rowSigmaAll_otherRowsSigma
#print axioms RandomTriangle.D_eq_sup
#print axioms mack1_of_mack1Row
#print axioms mack3_of_mack3Row
#print axioms condExp_eps_rowSigma
#print axioms mack2'_of_rows
#print axioms NontrivialModel.condExp_ultimate_bot
#print axioms NontrivialModel.crossFree_ultimates
#print axioms NontrivialModel.ultimate_nontrivial
#print axioms NontrivialModel.exists_crossFree_nondegenerate

#print axioms fhatW_eq_weighted_average
#print axioms weighted_sq_devW
#print axioms weighted_sq_devW_at_fhatW
#print axioms ChatW_succ
#print axioms ChatW_diag
#print axioms msepW_eq_sum_mackTermW
#print axioms se2recW_step
#print axioms se2recW_eq_closed
#print axioms se2recW_eq_msepW
#print axioms SW_unit
#print axioms TW_unit
#print axioms fhatW_unit
#print axioms sigma2W_unit
#print axioms ChatW_unit
#print axioms ultimateW_unit
#print axioms mackTermW_unit
#print axioms msepW_unit
#print axioms se2recW_unit
#print axioms se2recW_eq_msep_unit
#print axioms RandomTriangle.SWrv_eq_sum
#print axioms RandomTriangle.stronglyMeasurable_SWrv
#print axioms RandomTriangle.stronglyMeasurable_gW
#print axioms RandomTriangle.fhatWrv_eq
#print axioms condExp_fhatWrv
#print axioms RandomTriangle.stronglyMeasurable_weightVolume
#print axioms RandomTriangle.fhatWrv_sub_eq
#print axioms RandomTriangle.sq_fhatWrv_sub
#print axioms condExp_sq_fhatWrv_sub
#print axioms condVar_fhatWrv
#print axioms weighted_sq_devW_factorResidual
#print axioms RandomTriangle.sigma2Wrv_eq
#print axioms condExp_wssWrv
#print axioms condExp_sigma2Wrv

#print axioms mem_obsRow
#print axioms mem_obsCol
#print axioms obsCol_succ
#print axioms sum_incr
#print axioms sum_incr_obsRow
#print axioms sum_incr_obsCol_succ
#print axioms CLcum_diag
#print axioms CLcum_eq_div
#print axioms CLcum_eq_ultimate_div
#print axioms sum_CLincr
#print axioms chainLadder_fitted_row_totals
#print axioms chainLadder_fitted_row_totals_eq
#print axioms sum_CLcum_obsCol_aux
#print axioms sum_CLcum_obsCol
#print axioms sum_CLcum_contributors
#print axioms chainLadder_fitted_column_totals
#print axioms chainLadder_scoreEquations
#print axioms hasDerivAt_rowQuasiLogLik
#print axioms hasDerivAt_colQuasiLogLik
#print axioms deriv_rowQuasiLogLik_eq_zero_iff
#print axioms deriv_colQuasiLogLik_eq_zero_iff
#print axioms sum_multFit_obsRow
#print axioms sum_multFit_obsCol
#print axioms mult_row_eq
#print axioms sum_mult_patternCum_aux
#print axioms sum_mult_patternCum
#print axioms patternCum_pos
#print axioms patternCum_mul_fhat
#print axioms patternCum_mul_prod
#print axioms fhat_pos_of_mult
#print axioms mult_cum_eq_CLcum
#print axioms multFit_eq_CLincr

#print axioms IndependenceWitness.rowsGenerateD
#print axioms IndependenceWitness.measurableSet_shockEvent
#print axioms IndependenceWitness.measure_shockEvent
#print axioms IndependenceWitness.iIndepSet_shockEvent_fin
#print axioms IndependenceWitness.iIndepSet_shockEvent
#print axioms IndependenceWitness.stronglyMeasurable_Cw_xi
#print axioms IndependenceWitness.rowsIndep
#print axioms IndependenceWitness.rowSigma_zero
#print axioms IndependenceWitness.mack1Row
#print axioms IndependenceWitness.mack1_from_rows
#print axioms IndependenceWitness.mack2'_from_rows
#print axioms IndependenceWitness.nontrivial
#print axioms IndependenceWitness.exists_independence_witness

#print axioms condExp_sq_trueCDR
#print axioms condVar_trueCDR
#print axioms S_succ_eq
#print axioms mwMsepCDR_eq_mwMsepObsCDR_add_mwVarCDR
#print axioms mwMsepObsCDR_le_mwMsepCDR
#print axioms mw_term_split
#print axioms mwMsepCDR_eq_display
#print axioms mwVarCDR_eq_plugin
#print axioms mwProcessCDR_eq_plugin
#print axioms sum_range_cdrProcVar_eq_procVar
#print axioms sum_procVar_step_eq_procVar
#print axioms condExp_sum_cdrProcVar_eq_procVar
#print axioms mwMsepTotalCDR_sub_mwMsepTotalObsCDR
#print axioms RandomTriangle.rowSigma_le_obsSigma
#print axioms RandomTriangle.rowSigma_le_otherObs
#print axioms RandomTriangle.obsSigma_le
#print axioms RandomTriangle.otherObs_le_otherRowsAll
#print axioms RandomTriangle.otherObs_le
#print axioms RandomTriangle.obsSigma_eq_sup
#print axioms RandomTriangle.stronglyMeasurable_obsSigma_C
#print axioms RandomTriangle.stronglyMeasurable_obsSigma_Srv
#print axioms RandomTriangle.stronglyMeasurable_obsSigma_fhatRv
#print axioms RandomTriangle.stronglyMeasurable_obsSigma_ChatRv
#print axioms indep_rowSigmaAll_otherObs
#print axioms condExp_obsSigma_eq_rowSigma
#print axioms condExp_D_eq_rowSigma
#print axioms condExp_obsSigma_eq_D
#print axioms condExp_C_obsSigma_eq_D
#print axioms condExp_sq_C_obsSigma_eq_D
#print axioms condMsep_eq_of_rows
#print axioms condExp_cross_obsSigma_eq_zero
#print axioms condCrossFree_of_rows
#print axioms condMsepTotal_eq_of_rows
#print axioms sum_procVar_le_condMsepTotal_of_rows
#print axioms IndependenceWitness.memLp_all
#print axioms IndependenceWitness.condExp_obsSigma_eq_D_of_witness
#print axioms IndependenceWitness.condCrossFree_obs_of_rows
#print axioms taylorAshe_fhat_0
#print axioms taylorAshe_fhat_1
#print axioms taylorAshe_fhat_2
#print axioms taylorAshe_fhat_3
#print axioms taylorAshe_fhat_4
#print axioms taylorAshe_fhat_5
#print axioms taylorAshe_fhat_6
#print axioms taylorAshe_fhat_7
#print axioms taylorAshe_fhat_8
#print axioms taylorAshe_sigma2_0
#print axioms taylorAshe_sigma2_1
#print axioms taylorAshe_sigma2_2
#print axioms taylorAshe_sigma2_3
#print axioms taylorAshe_sigma2_4
#print axioms taylorAshe_sigma2_5
#print axioms taylorAshe_sigma2_6
#print axioms taylorAshe_sigma2_7
#print axioms taylorAshe_total_reserve_rounds

#print axioms spearmanRho_eq_one_sub_six_mul_sum_sq_div
#print axioms spearmanPermutationMean_eq_zero
#print axioms spearmanPermutationVariance_eq
#print axioms calendarNullMean_eq_mackCalendarNullMean
#print axioms calendarNullSecondMoment_closed
#print axioms calendarNullVariance_eq_mackCalendarNullVariance
#print axioms sum_fairSignMass
#print axioms calendarNullMean_five
#print axioms calendarNullSecondMoment_five
#print axioms calendarNullVariance_five
#print axioms mackCalendarNullMoments_five
#print axioms mackLognormal_mean_eq
#print axioms mackLognormal_variance_eq
#print axioms condExp_bfReservePriorRv
#print axioms condVar_bfReservePriorRv
#print axioms buhlmannStraub_weighted_sq_dev
#print axioms buhlmannStraubEstimate_normal_eq
#print axioms buhlmannStraubLoss_eq_at_estimate_add
#print axioms buhlmannStraubEstimate_minimizes
#print axioms buhlmannStraubEstimate_eq_credibility
#print axioms buhlmannStraubCredibility_mem_Icc

#print axioms buhlmannStraubWeightedMeanRv_sub_riskMean
#print axioms condExp_buhlmannStraubResidual_eq_zero
#print axioms condExp_sq_buhlmannStraubWeightedResidualTotal
#print axioms condExp_buhlmannStraubWeightedResidualTotal_eq_zero
#print axioms integral_buhlmannStraubWeightedResidualTotal_eq_zero
#print axioms integral_buhlmannStraubPredictor_eq_collectiveMean
#print axioms integral_sq_buhlmannStraubWeightedMeanRv_sub_riskMean
#print axioms integral_buhlmannStraubRiskMean_mul_weightedResidual_eq_zero
#print axioms buhlmannStraubExpectedSqLoss_eq
#print axioms buhlmannStraubExpectedSqLoss_scaled_eq_riskQuadratic
#print axioms buhlmannStraubRiskQuadratic_eq_at_credibility_add
#print axioms buhlmannStraubCredibility_minimizes_riskQuadratic
#print axioms buhlmannStraubCredibility_minimizes_expectedSqLoss
#print axioms buhlmannStraubPredictor_credibility_eq_estimate
#print axioms BuhlmannStraubWitness.processShock_integrable
#print axioms BuhlmannStraubWitness.processShock_memLp
#print axioms BuhlmannStraubWitness.integral_eq_average
#print axioms BuhlmannStraubWitness.latentSigma_eq_bot
#print axioms BuhlmannStraubWitness.condExp_bot_eq_average
#print axioms BuhlmannStraubWitness.observation_nondegenerate
#print axioms BuhlmannStraubWitness.momentModel
#print axioms BuhlmannStraubWitness.exists_process_nondegenerate_buhlmannStraubModel
