import VerifiedReserving.Independence
import VerifiedReserving.ObservedData
import VerifiedReserving.Test.NontrivialModel

/-!
# A finite witness for independence across accident years

The nontrivial model already has one Rademacher shock per accident year on
eight equiprobable outcomes.  This file verifies the stronger row-level
hypotheses from `Independence.lean`: the row sigma-algebras are mutually
independent and their observed histories generate the filtration.  These are
the finite-model forms of Mack (1993), equations (1) and (2), and the `B_k`
filtration used in the proof of Theorem 2 on pp. 214-216.
-/

open MeasureTheory Finset Filter ProbabilityTheory

namespace VerifiedReserving.IndependenceWitness

noncomputable section

open NontrivialModel

/-- The observed-data sigma-algebra generated by every accident year's
claims through development year `k`.  This is Mack's `B_k` in the proof of
Theorem 2 (Mack 1993, pp. 215-216). -/
@[reducible]
def Dgen (k : ℕ) : MeasurableSpace Ω :=
  ⨆ i, ⨆ j, ⨆ (_ : j ≤ k), MeasurableSpace.comap (Cw i j) inferInstance

/-- The eight-outcome random triangle equipped with its row-generated
observed-data filtration, used to realize Mack (1993), equations (1)-(2). -/
def X : RandomTriangle Ω 3 where
  C := Cw
  D := Dgen
  D_le := fun _ =>
    iSup_le fun i => iSup_le fun j => iSup_le fun _ => (measurable_of_countable (Cw i j)).comap_le
  D_mono := by
    intro a b hab
    exact iSup_le fun i => iSup_le fun j => iSup_le fun hj =>
      le_iSup_of_le i (le_iSup_of_le j (le_iSup_of_le (hj.trans hab) le_rfl))
  meas := fun i j k hjk => by
    have hproof : MeasurableSpace.comap (Cw i j) inferInstance ≤
        ⨆ (_ : j ≤ k), MeasurableSpace.comap (Cw i j) inferInstance :=
      le_iSup_of_le hjk le_rfl
    have hj : MeasurableSpace.comap (Cw i j) inferInstance ≤
        ⨆ j, ⨆ (_ : j ≤ k), MeasurableSpace.comap (Cw i j) inferInstance :=
      le_iSup_of_le j hproof
    have hi : MeasurableSpace.comap (Cw i j) inferInstance ≤ Dgen k :=
      le_iSup_of_le i hj
    exact (Measurable.of_comap_le hi).stronglyMeasurable

/-- The witness filtration is exactly the join of the row histories, as in
Mack's `B_k` construction in the proof of Theorem 2 (1993, pp. 215-216). -/
theorem rowsGenerateD : RowsGenerateD X := by
  intro k
  change (⨆ i, ⨆ j, ⨆ (_ : j ≤ k), MeasurableSpace.comap (Cw i j) inferInstance) =
    ⨆ i, ⨆ j, ⨆ (_ : j ≤ k), MeasurableSpace.comap (Cw i j) inferInstance
  rfl

/-- The positive-shock event for accident year `i`.  These are the three
independent coordinate events realizing Mack (1993), equation (2), p. 215;
out-of-range rows carry the empty event. -/
def shockEvent (i : ℕ) : Set Ω := { ω | xi i ω = 1 }

theorem measurableSet_shockEvent (i : ℕ) : MeasurableSet (shockEvent i) :=
  MeasurableSpace.measurableSet_top

theorem measure_shockEvent (i : ℕ) :
    μ (shockEvent i) = if i < 3 then (2 : ENNReal)⁻¹ else 0 := by
  have hhalf : (8 : ENNReal)⁻¹ * 4 = (2 : ENNReal)⁻¹ := by
    change (((8 : NNReal) : ENNReal)⁻¹ * ((4 : NNReal) : ENNReal)) =
      (((2 : NNReal) : ENNReal)⁻¹)
    rw [← ENNReal.coe_inv (by norm_num : (8 : NNReal) ≠ 0),
      ← ENNReal.coe_inv (by norm_num : (2 : NNReal) ≠ 0), ← ENNReal.coe_mul]
    norm_num
  rcases i with (_ | _ | _ | i)
  · have h : shockEvent 0 = ({0, 2, 4, 6} : Finset Ω) := by
      ext ω
      fin_cases ω <;> simp [shockEvent, xi] <;> norm_num
    rw [h]
    simp only [μ, Measure.smul_apply, smul_eq_mul]
    rw [Measure.count_apply_finset]
    have : #({0, 2, 4, 6} : Finset Ω) = 4 := by decide
    rw [this]
    simp only [if_pos (by omega : 0 < 3)]
    exact hhalf
  · have h : shockEvent 1 = ({0, 1, 4, 5} : Finset Ω) := by
      ext ω
      fin_cases ω <;> simp [shockEvent, xi] <;> norm_num
    rw [h]
    simp only [μ, Measure.smul_apply, smul_eq_mul]
    rw [Measure.count_apply_finset]
    have : #({0, 1, 4, 5} : Finset Ω) = 4 := by decide
    rw [this]
    simp only [if_pos (by omega : 1 < 3)]
    exact hhalf
  · have h : shockEvent 2 = ({0, 1, 2, 3} : Finset Ω) := by
      ext ω
      fin_cases ω <;> simp [shockEvent, xi] <;> norm_num
    rw [h]
    simp only [μ, Measure.smul_apply, smul_eq_mul]
    rw [Measure.count_apply_finset]
    have : #({0, 1, 2, 3} : Finset Ω) = 4 := by decide
    rw [this]
    simp only [if_pos (by omega : 2 < 3)]
    exact hhalf
  · simp [shockEvent, xi, μ]

theorem iIndepSet_shockEvent_fin :
    iIndepSet (fun i : Fin 3 => shockEvent i) μ := by
  refine (iIndepSet_iff_meas_biInter
    (f := fun i : Fin 3 => shockEvent i) (fun i => measurableSet_shockEvent i)).2 ?_
  have hquarter : (8 : ENNReal)⁻¹ * 2 = (2 : ENNReal)⁻¹ ^ 2 := by
    change (((8 : NNReal) : ENNReal)⁻¹ * ((2 : NNReal) : ENNReal)) =
      (((2 : NNReal) : ENNReal)⁻¹) ^ 2
    rw [← ENNReal.coe_inv (by norm_num : (8 : NNReal) ≠ 0),
      ← ENNReal.coe_inv (by norm_num : (2 : NNReal) ≠ 0),
      ← ENNReal.coe_mul, ← ENNReal.coe_pow]
    norm_num
  have heighth : (8 : ENNReal)⁻¹ * 1 = (2 : ENNReal)⁻¹ ^ 3 := by
    change (((8 : NNReal) : ENNReal)⁻¹ * ((1 : NNReal) : ENNReal)) =
      (((2 : NNReal) : ENNReal)⁻¹) ^ 3
    rw [← ENNReal.coe_inv (by norm_num : (8 : NNReal) ≠ 0),
      ← ENNReal.coe_inv (by norm_num : (2 : NNReal) ≠ 0),
      ← ENNReal.coe_mul, ← ENNReal.coe_pow]
    norm_num
  intro t
  fin_cases t <;> simp [measure_shockEvent]
  · have h : shockEvent 0 ∩ shockEvent 1 = ({0, 4} : Finset Ω) := by
      ext ω
      fin_cases ω <;> simp [shockEvent, xi] <;> norm_num
    rw [h]
    simp only [μ, Measure.smul_apply, smul_eq_mul]
    rw [Measure.count_apply_finset]
    have : #({0, 4} : Finset Ω) = 2 := by decide
    rw [this]
    exact hquarter
  · have h : shockEvent 0 ∩ shockEvent 2 = ({0, 2} : Finset Ω) := by
      ext ω
      fin_cases ω <;> simp [shockEvent, xi] <;> norm_num
    rw [h]
    simp only [μ, Measure.smul_apply, smul_eq_mul]
    rw [Measure.count_apply_finset]
    have : #({0, 2} : Finset Ω) = 2 := by decide
    rw [this]
    exact hquarter
  · have h : shockEvent 1 ∩ shockEvent 2 = ({0, 1} : Finset Ω) := by
      ext ω
      fin_cases ω <;> simp [shockEvent, xi] <;> norm_num
    rw [h]
    simp only [μ, Measure.smul_apply, smul_eq_mul]
    rw [Measure.count_apply_finset]
    have : #({0, 1} : Finset Ω) = 2 := by decide
    rw [this]
    exact hquarter
  · have h : shockEvent 0 ∩ (shockEvent 1 ∩ shockEvent 2) = ({0} : Finset Ω) := by
      ext ω
      fin_cases ω <;> simp [shockEvent, xi] <;> norm_num
    rw [h]
    simp only [μ, Measure.smul_apply, smul_eq_mul]
    rw [Measure.count_apply_finset]
    have : #({0} : Finset Ω) = 1 := by decide
    rw [this]
    simpa using heighth

/-- Mack's accident-year shocks are mutually independent, including the
trivial out-of-range rows.  This is the finite probability-space instance of
Mack (1993), equation (2), p. 215. -/
theorem iIndepSet_shockEvent : iIndepSet shockEvent μ := by
  refine (iIndepSet_iff_meas_biInter measurableSet_shockEvent).2 ?_
  intro t
  by_cases hlarge : ∃ i ∈ t, 3 ≤ i
  · obtain ⟨i, hit, hi⟩ := hlarge
    have hi' : ¬ i < 3 := by omega
    have hevent : shockEvent i = ∅ := by
      rcases i with (_ | _ | _ | i) <;> simp_all [shockEvent, xi]
    have hinter : (⋂ j ∈ t, shockEvent j) = ∅ := by
      ext ω
      constructor
      · intro hω
        have hmem : ω ∈ shockEvent i := Set.mem_iInter.mp (Set.mem_iInter.mp hω i) hit
        rw [hevent] at hmem
        exact hmem
      · simp
    have hmeasure : μ (shockEvent i) = 0 := by simp [measure_shockEvent, hi']
    rw [hinter, measure_empty]
    exact (Finset.prod_eq_zero hit hmeasure).symm
  · have hsmall : ∀ i ∈ t, i < 3 := by
      intro i hit
      by_contra hi
      exact hlarge ⟨i, hit, by omega⟩
    by_cases h0 : 0 ∈ t
    · by_cases h1 : 1 ∈ t
      · by_cases h2 : 2 ∈ t
        · have ht : t = {0, 1, 2} := by
            ext i
            constructor
            · intro hi
              have hi' := hsmall i hi
              interval_cases i <;> simp_all
            · intro hi
              simp only [mem_insert, mem_singleton] at hi
              rcases hi with rfl | rfl | rfl <;> assumption
          subst t
          simpa [measure_shockEvent, pow_two, pow_succ, mul_assoc, mul_comm, mul_left_comm] using
            iIndepSet_shockEvent_fin.meas_biInter ({0, 1, 2} : Finset (Fin 3))
        · have ht : t = {0, 1} := by
            ext i
            constructor
            · intro hi
              have hi' := hsmall i hi
              interval_cases i <;> simp_all
            · intro hi
              simp only [mem_insert, mem_singleton] at hi
              rcases hi with rfl | rfl <;> assumption
          subst t
          simpa [measure_shockEvent, pow_two] using
            iIndepSet_shockEvent_fin.meas_biInter ({0, 1} : Finset (Fin 3))
      · by_cases h2 : 2 ∈ t
        · have ht : t = {0, 2} := by
            ext i
            constructor
            · intro hi
              have hi' := hsmall i hi
              interval_cases i <;> simp_all
            · intro hi
              simp only [mem_insert, mem_singleton] at hi
              rcases hi with rfl | rfl <;> assumption
          subst t
          simpa [measure_shockEvent, pow_two] using
            iIndepSet_shockEvent_fin.meas_biInter ({0, 2} : Finset (Fin 3))
        · have ht : t = {0} := by
            ext i
            constructor
            · intro hi
              have hi' := hsmall i hi
              interval_cases i <;> simp_all
            · intro hi
              simp only [mem_singleton] at hi
              subst i
              exact h0
          subst t
          simp
    · by_cases h1 : 1 ∈ t
      · by_cases h2 : 2 ∈ t
        · have ht : t = {1, 2} := by
            ext i
            constructor
            · intro hi
              have hi' := hsmall i hi
              interval_cases i <;> simp_all
            · intro hi
              simp only [mem_insert, mem_singleton] at hi
              rcases hi with rfl | rfl <;> assumption
          subst t
          simpa [measure_shockEvent, pow_two] using
            iIndepSet_shockEvent_fin.meas_biInter ({1, 2} : Finset (Fin 3))
        · have ht : t = {1} := by
            ext i
            constructor
            · intro hi
              have hi' := hsmall i hi
              interval_cases i <;> simp_all
            · intro hi
              simp only [mem_singleton] at hi
              subst i
              exact h1
          subst t
          simp

      · by_cases h2 : 2 ∈ t
        · have ht : t = {2} := by
            ext i
            constructor
            · intro hi
              have hi' := hsmall i hi
              interval_cases i <;> simp_all
            · intro hi
              simp only [mem_singleton] at hi
              subst i
              exact h2
          subst t
          simp
        · have ht : t = ∅ := by
            ext i
            constructor
            · intro hi
              have hi' := hsmall i hi
              interval_cases i <;> simp_all
            · simp
          subst t
          simp

/-- Every claim in row `i` is measurable with respect to that row's shock,
the reduction used to verify Mack (1993), equation (2), p. 215. -/
theorem stronglyMeasurable_Cw_xi (i k : ℕ) :
    StronglyMeasurable[MeasurableSpace.comap (xi i) inferInstance] (Cw i k) := by
  by_cases hk : k = 0
  · subst k
    rw [Cw_zero]
    exact stronglyMeasurable_const
  · have hxi : StronglyMeasurable[MeasurableSpace.comap (xi i) inferInstance] (xi i) :=
      (Measurable.of_comap_le le_rfl).stronglyMeasurable
    rw [show Cw i k = fun ω => c * fdev ^ k * (1 + s * xi i ω) by
      ext ω
      simp [Cw, hk]]
    exact stronglyMeasurable_const.mul
      (stronglyMeasurable_const.add (stronglyMeasurable_const.mul hxi))

/-- The accident-year row sigma-algebras of the eight-outcome witness are
mutually independent.  This realizes Mack (1993), equation (2), p. 215. -/
theorem rowsIndep : RowsIndep X μ := by
  have hindicator : iIndepFun
      (fun i => (shockEvent i).indicator fun _ => (1 : ℝ)) μ :=
    iIndepSet_shockEvent.iIndepFun_indicator
  let toShock : ℕ → ℝ → ℝ := fun i x => if i < 3 then 2 * x - 1 else 0
  have htoShock : ∀ i, Measurable (toShock i) := by
    intro i
    by_cases hi : i < 3
    · simp only [toShock, hi, if_true]
      fun_prop
    · simp only [toShock, hi, if_false]
      fun_prop
  have hcomposed := hindicator.comp toShock htoShock
  have hxi : iIndepFun xi μ := by
    apply hcomposed.congr
    intro i
    refine Eventually.of_forall fun ω => ?_
    rcases i with (_ | _ | _ | i) <;> fin_cases ω <;>
      simp [toShock, shockEvent, xi] <;> norm_num
  exact iIndep_of_iIndep_of_le hxi.iIndep fun i => by
    change (⨆ j, MeasurableSpace.comap (Cw i j) inferInstance) ≤
      MeasurableSpace.comap (xi i) inferInstance
    exact iSup_le fun j => (stronglyMeasurable_Cw_xi i j).measurable.comap_le

theorem rowSigma_zero (i : ℕ) : X.rowSigma i 0 = ⊥ := by
  apply le_antisymm
  · refine iSup_le fun j => iSup_le fun hj => ?_
    have hj0 : j = 0 := Nat.eq_zero_of_le_zero hj
    subst j
    change MeasurableSpace.comap (Cw i 0) inferInstance ≤ ⊥
    rw [Cw_zero, MeasurableSpace.comap_const]
  · exact bot_le

/-- The witness satisfies Mack's row-conditioned mean assumption, equation
(1) in Mack (1993), p. 214. -/
theorem mack1Row : Mack1Row X μ f := by
  intro i hi k
  cases k with
  | zero =>
      show μ[Cw i 1 | X.rowSigma i 0] =ᵐ[μ] fun ω => f 0 * Cw i 0 ω
      rw [rowSigma_zero, ← Dfil_zero, condExp_bot_eq_sum, sum_Cw_one i hi, Cw_zero]
      refine Eventually.of_forall fun _ => ?_
      simp only [f]
      ring
  | succ k =>
      show μ[Cw i (k + 2) | X.rowSigma i (k + 1)] =ᵐ[μ]
        fun ω => f (k + 1) * Cw i (k + 1) ω
      have hstep : Cw i (k + 2) = fun ω => f (k + 1) * Cw i (k + 1) ω := by
        ext ω
        rw [Cw_succ, Cw_succ]
        simp only [f]
        ring
      rw [hstep]
      exact EventuallyEq.of_eq (condExp_of_stronglyMeasurable
        (X.rowSigma_le i (k + 1))
        (stronglyMeasurable_const.mul (X.stronglyMeasurable_rowSigma i le_rfl))
        (integrable_all _))

/-- Mack's `D_k`-conditioned mean assumption follows on the witness from
the row-conditioned equation (1) and accident-year independence (2). -/
theorem mack1_from_rows : Mack1 X μ f :=
  mack1_of_mack1Row X f rowsGenerateD rowsIndep mack1Row (fun _ _ => integrable_all _)

/-- Mack's cross-row residual condition follows on the witness from the
row-conditioned equation (1) and accident-year independence (2). -/
theorem mack2'_from_rows : Mack2' X μ f :=
  mack2'_of_rows X f rowsGenerateD rowsIndep mack1Row
    (fun _ _ => integrable_all _) (fun _ _ _ => integrable_all _)

/-- The witness for Mack (1993), equations (1)-(2), is genuinely random: two
outcomes give different first-developed claims in accident year zero. -/
theorem nontrivial : X.C 0 1 (0 : Ω) ≠ X.C 0 1 (1 : Ω) :=
  NontrivialModel.nontrivial

/-- A single finite model simultaneously realizes Mack's independent-row
assumption (2), the row-generated filtration from the proof of Theorem 2,
the row-conditioned equation (1), and both derived `D_k` conclusions
(Mack 1993, pp. 214-216). -/
theorem exists_independence_witness :
    ∃ X' : RandomTriangle Ω 3,
      RowsIndep X' μ ∧ RowsGenerateD X' ∧ Mack1Row X' μ f ∧
        Mack1 X' μ f ∧ Mack2' X' μ f ∧
          ∃ ω₁ ω₂, X'.C 0 1 ω₁ ≠ X'.C 0 1 ω₂ :=
  ⟨X, rowsIndep, rowsGenerateD, mack1Row, mack1_from_rows, mack2'_from_rows,
    0, 1, nontrivial⟩

/-- Every real function on the eight-outcome space is square integrable. -/
theorem memLp_all (g : Ω → ℝ) : MemLp g 2 μ :=
  ⟨(measurable_of_countable g).aestronglyMeasurable, eLpNorm_lt_top_of_finite⟩

/-- **No further information about one accident year, on the witness.**  The
observed data and the row's development-year filtration at its latest diagonal
give the same conditional expectation of any entry of the row.  This is the
hypothesis Mack discharges in one sentence in the proof of Theorem 3
(1993, pp. 217-219). -/
theorem condExp_obsSigma_eq_D_of_witness {i : ℕ} (hi : i < 3) (k : ℕ) :
    μ[X.C i k | X.obsSigma] =ᵐ[μ] μ[X.C i k | X.D (3 - 1 - i)] :=
  condExp_C_obsSigma_eq_D X rowsGenerateD rowsIndep hi k (integrable_all _)

/-- **Mack's cross-term condition on the witness, from independence alone.**
The centred true ultimates of the three accident years are conditionally
uncorrelated given the observed data, by `condCrossFree_of_rows`; the same
model has genuinely random claims, so the condition does not hold for want of
randomness. -/
theorem condCrossFree_obs_of_rows :
    CondCrossFree μ X.obsSigma (Finset.range 3) fun i => X.C i 2 :=
  condCrossFree_of_rows X rowsIndep fun _ _ => memLp_all _

end

end VerifiedReserving.IndependenceWitness
