import VerifiedReserving.BornhuetterFerguson
import VerifiedReserving.ObservedData

/-!
# Uncertainty in the Bornhuetter-Ferguson prior

Mack (2008), "The Prediction Error of Bornhuetter/Ferguson," describes the a
priori ultimate estimate and the selected development pattern as practically
independent and uses the variance formula for a product of independent random
variables (Section 4, properties (b)-(e), pp. 94-95; Section 5, pp. 95-96).

Here the estimated development pattern is the chain-ladder pattern already
used by this repository's `bfReserve` specialization and is measurable for the
observed run-off triangle. The exact independence hypothesis below strengthens
Mack's practical-independence description. Under it, the reserve has exact
conditional mean and variance formulas given the triangle. This is the
prior-uncertainty component of Mack's product-variance calculation; it does
not assert the rest of his prediction-error approximation.
-/

open MeasureTheory ProbabilityTheory Finset Filter

namespace VerifiedReserving

noncomputable section

variable {Ω : Type*} [mΩ : MeasurableSpace Ω] {μ : Measure Ω} {n : ℕ}

/-- The random outstanding fraction `1 - 1 / cdf` used by `bfReserve`, with
the cumulative development factor calculated from the observed triangle.
Mack (2008), Section 2, p. 89, writes this fraction as `1 - z`. -/
def RandomTriangle.bfOutstandingFractionRv (X : RandomTriangle Ω n) (i : ℕ) : Ω → ℝ :=
  fun ω => 1 - 1 / cdf (X.at ω) n i

/-- The Bornhuetter-Ferguson reserve with a random a priori ultimate. Pointwise
this is `bfReserve (X.at ω) n i (U ω)`, Mack (2008), Section 2, p. 89. -/
def RandomTriangle.bfReservePriorRv
    (X : RandomTriangle Ω n) (i : ℕ) (U : Ω → ℝ) : Ω → ℝ :=
  X.bfOutstandingFractionRv i * U

/-- The sigma-algebra generated by the a priori ultimate is independent of the
observed triangle. This is the exact version of Mack's independence condition
for the prior and estimated pattern, strengthening property (b), p. 94. -/
def BFPriorIndependent
    (X : RandomTriangle Ω n) (μ : Measure Ω) (U : Ω → ℝ) : Prop :=
  Indep (MeasurableSpace.comap U inferInstance) X.obsSigma μ

private theorem RandomTriangle.bfReservePriorRv_apply
    (X : RandomTriangle Ω n) (i : ℕ) (U : Ω → ℝ) (ω : Ω) :
    X.bfReservePriorRv i U ω = bfReserve (X.at ω) n i (U ω) := by
  simp [RandomTriangle.bfReservePriorRv, RandomTriangle.bfOutstandingFractionRv,
    bfReserve, Pi.mul_apply, mul_comm]

private theorem RandomTriangle.stronglyMeasurable_bfOutstandingFractionRv
    (X : RandomTriangle Ω n) (i : ℕ) :
    StronglyMeasurable[X.obsSigma] (X.bfOutstandingFractionRv i) := by
  have hprod : StronglyMeasurable[X.obsSigma]
      (∏ k ∈ Ico (n - 1 - i) (n - 1), X.fhatRv k) :=
    Finset.stronglyMeasurable_prod _ fun k _ => X.stronglyMeasurable_obsSigma_fhatRv k
  have hcdf :
      (fun ω => cdf (X.at ω) n i) =
        ∏ k ∈ Ico (n - 1 - i) (n - 1), X.fhatRv k := by
    funext ω
    simp [cdf, RandomTriangle.fhatRv, Finset.prod_apply]
  have hcdfMeas : StronglyMeasurable[X.obsSigma] (fun ω => cdf (X.at ω) n i) := by
    rw [hcdf]
    exact hprod
  unfold RandomTriangle.bfOutstandingFractionRv
  simp only [one_div]
  change StronglyMeasurable[X.obsSigma]
    ((fun _ : Ω => (1 : ℝ)) - (fun ω => cdf (X.at ω) n i)⁻¹)
  exact stronglyMeasurable_const.sub (hcdfMeas.measurable.inv.stronglyMeasurable)

/-- Conditional on the observed triangle, a BF reserve with an independent
random prior has the same form with the prior replaced by its mean. This is
Mack's unbiased-product calculation in Section 4(d)-(e), pp. 94-95, written
conditionally on the estimated pattern. -/
theorem condExp_bfReservePriorRv [IsProbabilityMeasure μ]
    (X : RandomTriangle Ω n) (i : ℕ) (U : Ω → ℝ)
    (hUm : StronglyMeasurable U) (hindep : BFPriorIndependent X μ U)
    (hU : Integrable U μ) (hR : Integrable (X.bfReservePriorRv i U) μ) :
    μ[X.bfReservePriorRv i U | X.obsSigma] =ᵐ[μ]
      X.bfReservePriorRv i (fun _ => ∫ ω, U ω ∂μ) := by
  have hA := X.stronglyMeasurable_bfOutstandingFractionRv i
  have hpull :
      μ[X.bfReservePriorRv i U | X.obsSigma] =ᵐ[μ]
        X.bfOutstandingFractionRv i * μ[U | X.obsSigma] := by
    exact condExp_mul_of_stronglyMeasurable_left hA hR hU
  have hprior :
      μ[U | X.obsSigma] =ᵐ[μ] fun _ => ∫ ω, U ω ∂μ :=
    condExp_indep_eq hUm.measurable.comap_le X.obsSigma_le
      (comap_measurable U).stronglyMeasurable hindep
  refine hpull.trans ?_
  filter_upwards [hprior] with ω hω
  simp [RandomTriangle.bfReservePriorRv, Pi.mul_apply, hω]

/-- Conditional variance contributed by an independent random BF prior. Given
the observed triangle, the outstanding fraction is fixed, so the variance is
its square times `Var(U)`. This is the prior component of Mack's independent
product variance formula, Section 5, pp. 95-96. -/
private theorem condExp_sq_bfReservePriorRv_sub_mean [IsProbabilityMeasure μ]
    (X : RandomTriangle Ω n) (i : ℕ) (U : Ω → ℝ)
    (hUm : StronglyMeasurable U) (hindep : BFPriorIndependent X μ U)
    (hU2 : Integrable (fun ω => (U ω - ∫ ω, U ω ∂μ) ^ 2) μ)
    (hR2 : Integrable (fun ω =>
      (X.bfReservePriorRv i U ω -
        X.bfReservePriorRv i (fun _ => ∫ ω, U ω ∂μ) ω) ^ 2) μ) :
    μ[fun ω =>
      (X.bfReservePriorRv i U ω -
        X.bfReservePriorRv i (fun _ => ∫ ω, U ω ∂μ) ω) ^ 2 | X.obsSigma] =ᵐ[μ]
      fun ω => (X.bfOutstandingFractionRv i ω) ^ 2 * variance U μ := by
  let centeredU : Ω → ℝ := fun ω => U ω - ∫ ω, U ω ∂μ
  let A2 : Ω → ℝ := fun ω => (X.bfOutstandingFractionRv i ω) ^ 2
  have hpoint :
      (fun ω =>
        (X.bfReservePriorRv i U ω -
          X.bfReservePriorRv i (fun _ => ∫ ω, U ω ∂μ) ω) ^ 2) =
        A2 * fun ω => centeredU ω ^ 2 := by
    funext ω
    simp only [RandomTriangle.bfReservePriorRv, Pi.mul_apply, A2, centeredU]
    ring
  have hA2 : StronglyMeasurable[X.obsSigma] A2 := by
    exact (X.stronglyMeasurable_bfOutstandingFractionRv i).pow 2
  have hUcomap : StronglyMeasurable[MeasurableSpace.comap U inferInstance] U :=
    (comap_measurable U).stronglyMeasurable
  have hcenteredUm : StronglyMeasurable[MeasurableSpace.comap U inferInstance]
      (fun ω => centeredU ω ^ 2) := by
    exact (hUcomap.sub stronglyMeasurable_const).pow 2
  have hproduct : Integrable (A2 * fun ω => centeredU ω ^ 2) μ := by
    rw [← hpoint]
    exact hR2
  have hpull :
      μ[A2 * (fun ω => centeredU ω ^ 2) | X.obsSigma] =ᵐ[μ]
        A2 * μ[fun ω => centeredU ω ^ 2 | X.obsSigma] :=
    condExp_mul_of_stronglyMeasurable_left hA2 hproduct hU2
  have hprior :
      μ[fun ω => centeredU ω ^ 2 | X.obsSigma] =ᵐ[μ]
        fun _ => ∫ ω, centeredU ω ^ 2 ∂μ :=
    condExp_indep_eq hUm.measurable.comap_le X.obsSigma_le hcenteredUm hindep
  rw [hpoint]
  refine hpull.trans ?_
  filter_upwards [hprior] with ω hω
  simp [A2, centeredU, variance_eq_integral hUm.aemeasurable, Pi.mul_apply, hω]

/-- Conditional variance contributed by an independent random BF prior. Under
the square-integrability hypotheses, `condExp_bfReservePriorRv` identifies the
conditional mean and the variance is the observed outstanding fraction squared
times `Var(U)`. This is the prior component of Mack's independent product
variance formula, Section 5, pp. 95-96. -/
theorem condVar_bfReservePriorRv [IsProbabilityMeasure μ]
    (X : RandomTriangle Ω n) (i : ℕ) (U : Ω → ℝ)
    (hUm : StronglyMeasurable U) (hindep : BFPriorIndependent X μ U)
    (hUmem : MemLp U 2 μ) (hRmem : MemLp (X.bfReservePriorRv i U) 2 μ) :
    Var[X.bfReservePriorRv i U; μ | X.obsSigma] =ᵐ[μ]
      fun ω => (X.bfOutstandingFractionRv i ω) ^ 2 * variance U μ := by
  have hU : Integrable U μ := hUmem.integrable one_le_two
  have hR : Integrable (X.bfReservePriorRv i U) μ := hRmem.integrable one_le_two
  have hmean := condExp_bfReservePriorRv X i U hUm hindep hU hR
  have hsqEq :
      ((X.bfReservePriorRv i U - μ[X.bfReservePriorRv i U | X.obsSigma]) ^ 2) =ᵐ[μ]
        fun ω =>
          (X.bfReservePriorRv i U ω -
            X.bfReservePriorRv i (fun _ => ∫ ω, U ω ∂μ) ω) ^ 2 := by
    filter_upwards [hmean] with ω hω
    simp only [Pi.pow_apply, Pi.sub_apply]
    rw [hω]
  have hU2 : Integrable (fun ω => (U ω - ∫ ω, U ω ∂μ) ^ 2) μ := by
    change Integrable ((U - fun _ => ∫ ω, U ω ∂μ) ^ 2) μ
    exact (hUmem.sub (memLp_const _)).integrable_sq
  have hR2 : Integrable (fun ω =>
      (X.bfReservePriorRv i U ω -
        X.bfReservePriorRv i (fun _ => ∫ ω, U ω ∂μ) ω) ^ 2) μ := by
    have hcentered : Integrable
        ((X.bfReservePriorRv i U - μ[X.bfReservePriorRv i U | X.obsSigma]) ^ 2) μ :=
      (hRmem.sub (hRmem.condExp one_le_two)).integrable_sq
    exact hcentered.congr hsqEq
  rw [condVar]
  exact (condExp_congr_ae hsqEq).trans
    (condExp_sq_bfReservePriorRv_sub_mean X i U hUm hindep hU2 hR2)

end

end VerifiedReserving
