import VerifiedReserving.BuhlmannStraub
import VerifiedReserving.TotalMsep

/-!
# Stochastic Bühlmann-Straub credibility

Bühlmann and Straub, "Glaubwürdigkeit für Schadensätze" (1970), assume in
Sections 3 and 5 that a contract has a latent risk parameter, that its loss
ratios have a common conditional mean, and that their conditional variance is
`sigma^2(Theta) / P`. Section 6, pp. 118-120, minimizes expected
squared prediction error over unbiased linear predictors. Display (4), p. 123,
is the familiar credibility blend.

This file gives the one-risk moment calculation behind that blend. The model
records the conditional first and second moments actually consumed by the
proof. Conditional cross moments replace the source's stronger conditional
independence assumption. From those hypotheses the weighted experience has
conditional process variance `sigma^2(Theta) / P`. Averaging the latent
variance gives the structural process parameter `v`, so prediction loss for
the latent mean is

`(1 - z)^2 * w + z^2 * v / P`.

Multiplication by `P` gives the deterministic coefficient loss
`P * w * (1-z)^2 + v * z^2`. Completing its square produces
`z = P*w/(v+P*w)`, and the resulting predictor is exactly
`buhlmannStraubEstimate`. The collective mean and both variance components are
model parameters. Their empirical estimation in Section 7 is not used here.
-/

open MeasureTheory ProbabilityTheory Finset Filter

namespace VerifiedReserving

noncomputable section

variable {Ω ι Θ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
  {μ : Measure Ω}

/-- The sigma-algebra generated by the latent risk parameter `Theta` in
Bühlmann-Straub (1970), Sections 3 and 5. -/
@[implicit_reducible]
def buhlmannStraubLatentSigma (theta : Ω → Θ) : MeasurableSpace Ω :=
  MeasurableSpace.comap theta inferInstance

/-- The hypothetical mean `mu(Theta)` of the latent risk. -/
def buhlmannStraubRiskMean
    (theta : Ω → Θ) (hypotheticalMean : Θ → ℝ) : Ω → ℝ :=
  hypotheticalMean ∘ theta

/-- The latent process-variance function `sigma^2(Theta)` in
Bühlmann-Straub (1970), Section 3. -/
def buhlmannStraubRiskVariance
    (theta : Ω → Θ) (hypotheticalVariance : Θ → ℝ) : Ω → ℝ :=
  hypotheticalVariance ∘ theta

/-- The process residual `X_i - mu(Theta)` for one exposure period. -/
def buhlmannStraubResidual
    (theta : Ω → Θ) (hypotheticalMean : Θ → ℝ)
    (observation : ι → Ω → ℝ) (i : ι) : Ω → ℝ :=
  observation i - buhlmannStraubRiskMean theta hypotheticalMean

/-- The exposure-weighted observation mean as a random variable. -/
def buhlmannStraubWeightedMeanRv
    (sample : Finset ι) (weight : ι → ℝ)
    (observation : ι → Ω → ℝ) : Ω → ℝ :=
  fun omega => buhlmannStraubWeightedMean sample weight (fun i => observation i omega)

/-- The exposure-weighted sum of process residuals. -/
def buhlmannStraubWeightedResidualTotal
    (sample : Finset ι) (weight : ι → ℝ)
    (theta : Ω → Θ) (hypotheticalMean : Θ → ℝ)
    (observation : ι → Ω → ℝ) : Ω → ℝ :=
  fun omega => ∑ i ∈ sample,
    weight i * buhlmannStraubResidual theta hypotheticalMean observation i omega

/-- A linear credibility predictor of the latent mean. The scalar `z` is the
credibility assigned to the weighted individual experience. -/
def buhlmannStraubPredictor
    (sample : Finset ι) (weight : ι → ℝ)
    (observation : ι → Ω → ℝ) (collectiveMean z : ℝ) : Ω → ℝ :=
  fun omega => collectiveMean + z *
    (buhlmannStraubWeightedMeanRv sample weight observation omega - collectiveMean)

/-- Expected squared prediction loss for the latent hypothetical mean. This is
the objective minimized in Bühlmann-Straub (1970), Section 6. -/
def buhlmannStraubExpectedSqLoss
    (sample : Finset ι) (weight : ι → ℝ)
    (theta : Ω → Θ) (hypotheticalMean : Θ → ℝ)
    (observation : ι → Ω → ℝ) (collectiveMean z : ℝ)
    (μ : Measure Ω) : ℝ :=
  ∫ omega, (buhlmannStraubRiskMean theta hypotheticalMean omega -
    buhlmannStraubPredictor sample weight observation collectiveMean z omega) ^ 2 ∂μ

/-- The deterministic coefficient loss obtained by multiplying the expected
prediction loss by total exposure. -/
def buhlmannStraubRiskQuadratic
    (totalWeight processVariance betweenVariance z : ℝ) : ℝ :=
  totalWeight * betweenVariance * (1 - z) ^ 2 + processVariance * z ^ 2

/-- Conditional-moment form of the one-risk Bühlmann-Straub model.

The source assumes conditional independence at fixed latent parameters. The
proof needs only the displayed conditional means, inverse-exposure variances,
and vanishing conditional cross moments, so those weaker conditions are
recorded directly. -/
structure BuhlmannStraubMomentModel
    (sample : Finset ι) (weight : ι → ℝ)
    (theta : Ω → Θ) (hypotheticalMean hypotheticalVariance : Θ → ℝ)
    (observation : ι → Ω → ℝ)
    (collectiveMean processVariance betweenVariance : ℝ)
    (μ : Measure Ω) : Prop where
  latentSigma_le : buhlmannStraubLatentSigma theta ≤ ‹MeasurableSpace Ω›
  riskMean_measurable :
    StronglyMeasurable[buhlmannStraubLatentSigma theta]
      (buhlmannStraubRiskMean theta hypotheticalMean)
  riskMean_memLp : MemLp (buhlmannStraubRiskMean theta hypotheticalMean) 2 μ
  riskVariance_measurable :
    StronglyMeasurable[buhlmannStraubLatentSigma theta]
      (buhlmannStraubRiskVariance theta hypotheticalVariance)
  riskVariance_integrable :
    Integrable (buhlmannStraubRiskVariance theta hypotheticalVariance) μ
  observation_memLp : ∀ i ∈ sample, MemLp (observation i) 2 μ
  weight_pos : ∀ i ∈ sample, 0 < weight i
  condMean : ∀ i ∈ sample,
    μ[observation i | buhlmannStraubLatentSigma theta] =ᵐ[μ]
      buhlmannStraubRiskMean theta hypotheticalMean
  condVariance : ∀ i ∈ sample,
    μ[fun omega =>
      (buhlmannStraubResidual theta hypotheticalMean observation i omega) ^ 2 |
        buhlmannStraubLatentSigma theta] =ᵐ[μ]
      fun omega =>
        buhlmannStraubRiskVariance theta hypotheticalVariance omega / weight i
  condCross : ∀ i ∈ sample, ∀ j ∈ sample, i ≠ j →
    μ[buhlmannStraubResidual theta hypotheticalMean observation i *
        buhlmannStraubResidual theta hypotheticalMean observation j |
      buhlmannStraubLatentSigma theta] =ᵐ[μ] 0
  latentMean : ∫ omega, buhlmannStraubRiskMean theta hypotheticalMean omega ∂μ =
    collectiveMean
  processVarianceMean :
    ∫ omega, buhlmannStraubRiskVariance theta hypotheticalVariance omega ∂μ =
      processVariance
  latentVariance : ∫ omega,
      (buhlmannStraubRiskMean theta hypotheticalMean omega - collectiveMean) ^ 2 ∂μ =
    betweenVariance

private theorem BuhlmannStraubMomentModel.residual_memLp
    {sample : Finset ι} {weight : ι → ℝ}
    {theta : Ω → Θ} {hypotheticalMean hypotheticalVariance : Θ → ℝ}
    {observation : ι → Ω → ℝ}
    {collectiveMean processVariance betweenVariance : ℝ}
    (model : BuhlmannStraubMomentModel sample weight theta hypotheticalMean
      hypotheticalVariance
      observation collectiveMean processVariance betweenVariance μ)
    {i : ι} (hi : i ∈ sample) :
    MemLp (buhlmannStraubResidual theta hypotheticalMean observation i) 2 μ := by
  exact (model.observation_memLp i hi).sub model.riskMean_memLp

omit [MeasurableSpace Ω] [MeasurableSpace Θ] in
/-- The weighted observation mean differs from the latent mean by the weighted
residual total divided by total exposure. -/
theorem buhlmannStraubWeightedMeanRv_sub_riskMean
    (sample : Finset ι) (weight : ι → ℝ)
    (theta : Ω → Θ) (hypotheticalMean : Θ → ℝ)
    (observation : ι → Ω → ℝ)
    (hweight : buhlmannStraubTotalWeight sample weight ≠ 0) :
    buhlmannStraubWeightedMeanRv sample weight observation -
        buhlmannStraubRiskMean theta hypotheticalMean =
      fun omega =>
        buhlmannStraubWeightedResidualTotal sample weight theta hypotheticalMean
          observation omega / buhlmannStraubTotalWeight sample weight := by
  have hw : (∑ i ∈ sample, weight i) ≠ 0 := by
    simpa [buhlmannStraubTotalWeight] using hweight
  funext omega
  unfold buhlmannStraubWeightedMeanRv buhlmannStraubWeightedMean
    buhlmannStraubWeightedResidualTotal buhlmannStraubResidual
    buhlmannStraubWeightedTotal buhlmannStraubTotalWeight buhlmannStraubRiskMean
  simp only [Pi.sub_apply, Function.comp_apply]
  simp_rw [mul_sub]
  rw [sum_sub_distrib, ← sum_mul]
  field_simp [hw]

/-- Under the source's conditional-mean assumption, each process residual has
conditional mean zero given the latent risk parameter. -/
theorem condExp_buhlmannStraubResidual_eq_zero [IsProbabilityMeasure μ]
    {sample : Finset ι} {weight : ι → ℝ}
    {theta : Ω → Θ} {hypotheticalMean hypotheticalVariance : Θ → ℝ}
    {observation : ι → Ω → ℝ}
    {collectiveMean processVariance betweenVariance : ℝ}
    (model : BuhlmannStraubMomentModel sample weight theta hypotheticalMean
      hypotheticalVariance
      observation collectiveMean processVariance betweenVariance μ)
    {i : ι} (hi : i ∈ sample) :
    μ[buhlmannStraubResidual theta hypotheticalMean observation i |
        buhlmannStraubLatentSigma theta] =ᵐ[μ] 0 := by
  have hObs : Integrable (observation i) μ :=
    (model.observation_memLp i hi).integrable one_le_two
  have hRisk : Integrable (buhlmannStraubRiskMean theta hypotheticalMean) μ :=
    model.riskMean_memLp.integrable one_le_two
  have hsub := condExp_sub hObs hRisk (buhlmannStraubLatentSigma theta)
  have hRiskCond :
      μ[buhlmannStraubRiskMean theta hypotheticalMean |
          buhlmannStraubLatentSigma theta] =
        buhlmannStraubRiskMean theta hypotheticalMean :=
    condExp_of_stronglyMeasurable model.latentSigma_le
      model.riskMean_measurable hRisk
  rw [buhlmannStraubResidual]
  refine hsub.trans ?_
  filter_upwards [model.condMean i hi] with omega homega
  simp only [Pi.sub_apply, homega, hRiskCond, sub_self, Pi.zero_apply]

/-- The exposure-weighted residual total has conditional second moment
`sigma^2(Theta) * P` given the latent parameter. Averaging and dividing by
`P^2` gives the weighted mean process variance `v / P`, where
`v = E[sigma^2(Theta)]`. This is the one-risk specialization of the
normal-equation moment calculation on pp. 119-120. -/
theorem condExp_sq_buhlmannStraubWeightedResidualTotal
    [IsProbabilityMeasure μ]
    {sample : Finset ι} {weight : ι → ℝ}
    {theta : Ω → Θ} {hypotheticalMean hypotheticalVariance : Θ → ℝ}
    {observation : ι → Ω → ℝ}
    {collectiveMean processVariance betweenVariance : ℝ}
    (model : BuhlmannStraubMomentModel sample weight theta hypotheticalMean
      hypotheticalVariance
      observation collectiveMean processVariance betweenVariance μ) :
    μ[fun omega =>
        (buhlmannStraubWeightedResidualTotal sample weight theta hypotheticalMean
          observation omega) ^ 2 |
      buhlmannStraubLatentSigma theta] =ᵐ[μ]
      fun omega => buhlmannStraubRiskVariance theta hypotheticalVariance omega *
        buhlmannStraubTotalWeight sample weight := by
  let residual : ι → Ω → ℝ :=
    fun i => buhlmannStraubResidual theta hypotheticalMean observation i
  let scaledResidual : ι → Ω → ℝ := fun i omega => weight i * residual i omega
  have hScaledMem : ∀ i ∈ sample, MemLp (scaledResidual i) 2 μ := by
    intro i hi
    exact (model.residual_memLp hi).const_mul (weight i)
  have hCross : ∀ i ∈ sample, ∀ j ∈ sample, i ≠ j →
      μ[scaledResidual i * scaledResidual j |
        buhlmannStraubLatentSigma theta] =ᵐ[μ] 0 := by
    intro i hi j hj hij
    have hpoint : scaledResidual i * scaledResidual j =
        (weight i * weight j) • (residual i * residual j) := by
      funext omega
      simp [scaledResidual, residual, Pi.mul_apply, Pi.smul_apply, smul_eq_mul]
      ring
    rw [hpoint]
    refine (condExp_smul (weight i * weight j) (residual i * residual j)
      (buhlmannStraubLatentSigma theta)).trans ?_
    filter_upwards [model.condCross i hi j hj hij] with omega homega
    simp [Pi.smul_apply, smul_eq_mul, residual, homega]
  have hsum := condExp_sq_finsetSum_of_cross
    (D := buhlmannStraubLatentSigma theta) sample scaledResidual hScaledMem hCross
  have hdiag : ∀ i ∈ sample,
      μ[fun omega => (scaledResidual i omega) ^ 2 |
          buhlmannStraubLatentSigma theta] =ᵐ[μ]
        fun omega => buhlmannStraubRiskVariance theta hypotheticalVariance omega *
          weight i := by
    intro i hi
    have hpoint : (fun omega => (scaledResidual i omega) ^ 2) =
        (weight i) ^ 2 • fun omega => (residual i omega) ^ 2 := by
      funext omega
      simp [scaledResidual, Pi.smul_apply, smul_eq_mul]
      ring
    rw [hpoint]
    refine (condExp_smul ((weight i) ^ 2) (fun omega => (residual i omega) ^ 2)
      (buhlmannStraubLatentSigma theta)).trans ?_
    filter_upwards [model.condVariance i hi] with omega homega
    change (μ[fun omega => (residual i omega) ^ 2 |
      buhlmannStraubLatentSigma theta]) omega =
        buhlmannStraubRiskVariance theta hypotheticalVariance omega / weight i at homega
    simp only [Pi.smul_apply, smul_eq_mul]
    rw [homega]
    field_simp [(model.weight_pos i hi).ne']
  change μ[fun omega => (∑ i ∈ sample, scaledResidual i omega) ^ 2 |
      buhlmannStraubLatentSigma theta] =ᵐ[μ]
    fun omega => buhlmannStraubRiskVariance theta hypotheticalVariance omega *
      buhlmannStraubTotalWeight sample weight
  refine hsum.trans ?_
  have hdiagAll : ∀ᵐ omega ∂μ, ∀ i ∈ sample,
      (μ[fun omega => (scaledResidual i omega) ^ 2 |
        buhlmannStraubLatentSigma theta]) omega =
          buhlmannStraubRiskVariance theta hypotheticalVariance omega * weight i := by
    rw [eventually_all_finset]
    exact hdiag
  filter_upwards [hdiagAll] with omega homega
  calc
    ∑ i ∈ sample,
        (μ[fun omega => (scaledResidual i omega) ^ 2 |
          buhlmannStraubLatentSigma theta]) omega =
        ∑ i ∈ sample,
          buhlmannStraubRiskVariance theta hypotheticalVariance omega * weight i :=
      sum_congr rfl fun i hi => homega i hi
    _ = buhlmannStraubRiskVariance theta hypotheticalVariance omega *
        buhlmannStraubTotalWeight sample weight := by
      simp [buhlmannStraubTotalWeight, mul_sum]

/-- The exposure-weighted residual total has conditional mean zero given the
latent risk parameter. -/
theorem condExp_buhlmannStraubWeightedResidualTotal_eq_zero
    [IsProbabilityMeasure μ]
    {sample : Finset ι} {weight : ι → ℝ}
    {theta : Ω → Θ} {hypotheticalMean hypotheticalVariance : Θ → ℝ}
    {observation : ι → Ω → ℝ}
    {collectiveMean processVariance betweenVariance : ℝ}
    (model : BuhlmannStraubMomentModel sample weight theta hypotheticalMean
      hypotheticalVariance
      observation collectiveMean processVariance betweenVariance μ) :
    μ[buhlmannStraubWeightedResidualTotal sample weight theta hypotheticalMean
        observation | buhlmannStraubLatentSigma theta] =ᵐ[μ] 0 := by
  let residual : ι → Ω → ℝ :=
    fun i => buhlmannStraubResidual theta hypotheticalMean observation i
  let scaledResidual : ι → Ω → ℝ := fun i omega => weight i * residual i omega
  have hInt : ∀ i ∈ sample, Integrable (scaledResidual i) μ := by
    intro i hi
    exact ((model.residual_memLp hi).const_mul (weight i)).integrable one_le_two
  have hterm : ∀ i ∈ sample,
      μ[scaledResidual i | buhlmannStraubLatentSigma theta] =ᵐ[μ] 0 := by
    intro i hi
    have hpoint : scaledResidual i = weight i • residual i := by
      funext omega
      simp [scaledResidual, Pi.smul_apply, smul_eq_mul]
    rw [hpoint]
    refine (condExp_smul (weight i) (residual i)
      (buhlmannStraubLatentSigma theta)).trans ?_
    filter_upwards [condExp_buhlmannStraubResidual_eq_zero model hi] with omega homega
    simp [Pi.smul_apply, smul_eq_mul, residual, homega]
  have hsum := condExp_finsetSum hInt (buhlmannStraubLatentSigma theta)
  have htotal :
      buhlmannStraubWeightedResidualTotal sample weight theta hypotheticalMean observation =
        ∑ i ∈ sample, scaledResidual i := by
    funext omega
    simp [buhlmannStraubWeightedResidualTotal, scaledResidual, residual, Finset.sum_apply]
  rw [htotal]
  refine hsum.trans ?_
  have htermAll : ∀ᵐ omega ∂μ, ∀ i ∈ sample,
      (μ[scaledResidual i | buhlmannStraubLatentSigma theta]) omega = 0 := by
    rw [eventually_all_finset]
    exact hterm
  filter_upwards [htermAll] with omega homega
  simp only [Finset.sum_apply, Pi.zero_apply]
  exact sum_eq_zero fun i hi => homega i hi

/-- The exposure-weighted process residual has unconditional mean zero. -/
theorem integral_buhlmannStraubWeightedResidualTotal_eq_zero
    [IsProbabilityMeasure μ]
    {sample : Finset ι} {weight : ι → ℝ}
    {theta : Ω → Θ} {hypotheticalMean hypotheticalVariance : Θ → ℝ}
    {observation : ι → Ω → ℝ}
    {collectiveMean processVariance betweenVariance : ℝ}
    (model : BuhlmannStraubMomentModel sample weight theta hypotheticalMean
      hypotheticalVariance observation collectiveMean processVariance betweenVariance μ) :
    ∫ omega,
        buhlmannStraubWeightedResidualTotal sample weight theta hypotheticalMean
          observation omega ∂μ = 0 := by
  have hzero := condExp_buhlmannStraubWeightedResidualTotal_eq_zero model
  calc
    ∫ omega,
        buhlmannStraubWeightedResidualTotal sample weight theta hypotheticalMean
          observation omega ∂μ =
        ∫ omega,
          (μ[buhlmannStraubWeightedResidualTotal sample weight theta hypotheticalMean
              observation | buhlmannStraubLatentSigma theta]) omega ∂μ :=
      (integral_condExp model.latentSigma_le).symm
    _ = ∫ _ : Ω, 0 ∂μ := integral_congr_ae hzero
    _ = 0 := by simp

/-- Every scalar predictor in the credibility family is expectation-unbiased
for the latent hypothetical mean. This verifies the source's Section 6
constraint within the one-risk family. -/
theorem integral_buhlmannStraubPredictor_eq_collectiveMean
    [IsProbabilityMeasure μ]
    {sample : Finset ι} {weight : ι → ℝ}
    {theta : Ω → Θ} {hypotheticalMean hypotheticalVariance : Θ → ℝ}
    {observation : ι → Ω → ℝ}
    {collectiveMean processVariance betweenVariance : ℝ}
    (model : BuhlmannStraubMomentModel sample weight theta hypotheticalMean
      hypotheticalVariance observation collectiveMean processVariance betweenVariance μ)
    (z : ℝ) (hweight : buhlmannStraubTotalWeight sample weight ≠ 0) :
    ∫ omega,
        buhlmannStraubPredictor sample weight observation collectiveMean z omega ∂μ =
      collectiveMean := by
  let riskMean := buhlmannStraubRiskMean theta hypotheticalMean
  let total := buhlmannStraubWeightedResidualTotal sample weight theta
    hypotheticalMean observation
  let totalWeight := buhlmannStraubTotalWeight sample weight
  let experience := buhlmannStraubWeightedMeanRv sample weight observation
  have hRiskInt : Integrable riskMean μ :=
    model.riskMean_memLp.integrable one_le_two
  have hTotalMem : MemLp total 2 μ := by
    unfold total buhlmannStraubWeightedResidualTotal
    exact memLp_finsetSum sample fun i hi =>
      (model.residual_memLp hi).const_mul (weight i)
  have hTotalInt : Integrable total μ := hTotalMem.integrable one_le_two
  have hProcessInt : Integrable (fun omega => totalWeight⁻¹ * total omega) μ :=
    hTotalInt.const_mul totalWeight⁻¹
  have hMeanIdentity := buhlmannStraubWeightedMeanRv_sub_riskMean sample weight theta
    hypotheticalMean observation hweight
  have hExperiencePoint : experience = fun omega =>
      riskMean omega + totalWeight⁻¹ * total omega := by
    funext omega
    have homega := congr_fun hMeanIdentity omega
    simp only [Pi.sub_apply] at homega
    change experience omega - riskMean omega = total omega / totalWeight at homega
    rw [div_eq_inv_mul] at homega
    linarith
  have hExperienceInt : Integrable experience μ := by
    rw [hExperiencePoint]
    exact hRiskInt.add hProcessInt
  have hTotalZero : ∫ omega, total omega ∂μ = 0 := by
    simpa [total] using integral_buhlmannStraubWeightedResidualTotal_eq_zero model
  have hExperienceMean : ∫ omega, experience omega ∂μ = collectiveMean := by
    rw [hExperiencePoint, integral_add hRiskInt hProcessInt, integral_const_mul,
      model.latentMean, hTotalZero]
    ring
  unfold buhlmannStraubPredictor
  change ∫ omega, collectiveMean + z * (experience omega - collectiveMean) ∂μ = _
  have hCenteredInt : Integrable (fun omega => experience omega - collectiveMean) μ :=
    hExperienceInt.sub (integrable_const _)
  have hScaledInt : Integrable (fun omega => z * (experience omega - collectiveMean)) μ :=
    hCenteredInt.const_mul z
  calc
    ∫ omega, collectiveMean + z * (experience omega - collectiveMean) ∂μ =
        (∫ _ : Ω, collectiveMean ∂μ) +
          ∫ omega, z * (experience omega - collectiveMean) ∂μ :=
      integral_add (integrable_const _) hScaledInt
    _ = collectiveMean + z *
        ((∫ omega, experience omega ∂μ) - ∫ _ : Ω, collectiveMean ∂μ) := by
      rw [integral_const_mul, integral_sub hExperienceInt (integrable_const _)]
      simp
    _ = collectiveMean := by rw [hExperienceMean]; simp

/-- The exposure-weighted observation mean has process variance `v / P`
around the latent hypothetical mean. -/
theorem integral_sq_buhlmannStraubWeightedMeanRv_sub_riskMean
    [IsProbabilityMeasure μ]
    {sample : Finset ι} {weight : ι → ℝ}
    {theta : Ω → Θ} {hypotheticalMean hypotheticalVariance : Θ → ℝ}
    {observation : ι → Ω → ℝ}
    {collectiveMean processVariance betweenVariance : ℝ}
    (model : BuhlmannStraubMomentModel sample weight theta hypotheticalMean
      hypotheticalVariance
      observation collectiveMean processVariance betweenVariance μ)
    (hweight : buhlmannStraubTotalWeight sample weight ≠ 0) :
    ∫ omega,
        (buhlmannStraubWeightedMeanRv sample weight observation omega -
          buhlmannStraubRiskMean theta hypotheticalMean omega) ^ 2 ∂μ =
      processVariance / buhlmannStraubTotalWeight sample weight := by
  let total := buhlmannStraubWeightedResidualTotal sample weight theta
    hypotheticalMean observation
  let totalWeight := buhlmannStraubTotalWeight sample weight
  have hcond := condExp_sq_buhlmannStraubWeightedResidualTotal model
  have htotalSq : ∫ omega, (total omega) ^ 2 ∂μ = processVariance * totalWeight := by
    calc
      ∫ omega, (total omega) ^ 2 ∂μ =
          ∫ omega, (μ[fun omega => (total omega) ^ 2 |
            buhlmannStraubLatentSigma theta]) omega ∂μ :=
        (integral_condExp model.latentSigma_le).symm
      _ = ∫ omega,
          buhlmannStraubRiskVariance theta hypotheticalVariance omega *
            totalWeight ∂μ := by
        exact integral_congr_ae hcond
      _ = processVariance * totalWeight := by
        rw [integral_mul_const, model.processVarianceMean]
  have hmean := buhlmannStraubWeightedMeanRv_sub_riskMean sample weight theta
    hypotheticalMean observation hweight
  have hpoint :
      (fun omega =>
        (buhlmannStraubWeightedMeanRv sample weight observation omega -
          buhlmannStraubRiskMean theta hypotheticalMean omega) ^ 2) =
        fun omega => totalWeight⁻¹ ^ 2 * (total omega) ^ 2 := by
    funext omega
    have homega := congr_fun hmean omega
    simp only [Pi.sub_apply] at homega
    rw [homega]
    simp [total, totalWeight, div_eq_inv_mul]
    ring
  rw [hpoint, integral_const_mul, htotalSq]
  dsimp only [totalWeight]
  field_simp [hweight]

/-- The centred latent mean is orthogonal to the weighted process residual.
This is the cross-term cancellation in the prediction-risk decomposition. -/
theorem integral_buhlmannStraubRiskMean_mul_weightedResidual_eq_zero
    [IsProbabilityMeasure μ]
    {sample : Finset ι} {weight : ι → ℝ}
    {theta : Ω → Θ} {hypotheticalMean hypotheticalVariance : Θ → ℝ}
    {observation : ι → Ω → ℝ}
    {collectiveMean processVariance betweenVariance : ℝ}
    (model : BuhlmannStraubMomentModel sample weight theta hypotheticalMean
      hypotheticalVariance
      observation collectiveMean processVariance betweenVariance μ) :
    ∫ omega,
        (buhlmannStraubRiskMean theta hypotheticalMean omega - collectiveMean) *
          buhlmannStraubWeightedResidualTotal sample weight theta hypotheticalMean
            observation omega ∂μ = 0 := by
  let centeredRisk : Ω → ℝ := fun omega =>
    buhlmannStraubRiskMean theta hypotheticalMean omega - collectiveMean
  let total := buhlmannStraubWeightedResidualTotal sample weight theta
    hypotheticalMean observation
  have hCenteredMeas : StronglyMeasurable[buhlmannStraubLatentSigma theta]
      centeredRisk := model.riskMean_measurable.sub stronglyMeasurable_const
  have hCenteredMem : MemLp centeredRisk 2 μ := by
    exact model.riskMean_memLp.sub (memLp_const collectiveMean)
  have hTotalMem : MemLp total 2 μ := by
    unfold total buhlmannStraubWeightedResidualTotal
    exact memLp_finsetSum sample fun i hi =>
      (model.residual_memLp hi).const_mul (weight i)
  have hProduct : Integrable (centeredRisk * total) μ :=
    hCenteredMem.integrable_mul hTotalMem
  have hTotalInt : Integrable total μ := hTotalMem.integrable one_le_two
  have hpull :
      μ[centeredRisk * total | buhlmannStraubLatentSigma theta] =ᵐ[μ]
        centeredRisk * μ[total | buhlmannStraubLatentSigma theta] :=
    condExp_mul_of_stronglyMeasurable_left hCenteredMeas hProduct hTotalInt
  have hzero := condExp_buhlmannStraubWeightedResidualTotal_eq_zero model
  change μ[total | buhlmannStraubLatentSigma theta] =ᵐ[μ] 0 at hzero
  calc
    ∫ omega, centeredRisk omega * total omega ∂μ =
        ∫ omega, (μ[centeredRisk * total |
          buhlmannStraubLatentSigma theta]) omega ∂μ :=
      (integral_condExp model.latentSigma_le).symm
    _ = ∫ _ : Ω, 0 ∂μ := by
      apply integral_congr_ae
      filter_upwards [hpull, hzero] with omega hp hz
      have hz' : (μ[total | buhlmannStraubLatentSigma theta]) omega = 0 := by
        simpa only [Pi.zero_apply] using hz
      rw [hp]
      simp [Pi.mul_apply, hz']
    _ = 0 := by simp

/-- **Bühlmann-Straub prediction-risk decomposition.** Under the latent moment
model, the expected squared loss of the credibility predictor with coefficient
`z` is

`(1-z)^2 * w + z^2 * v / P`.

This is the one-risk version of the mean-square criterion and normal-equation
calculation in Bühlmann-Straub (1970), Section 6, pp. 118-120. -/
theorem buhlmannStraubExpectedSqLoss_eq
    [IsProbabilityMeasure μ]
    {sample : Finset ι} {weight : ι → ℝ}
    {theta : Ω → Θ} {hypotheticalMean hypotheticalVariance : Θ → ℝ}
    {observation : ι → Ω → ℝ}
    {collectiveMean processVariance betweenVariance : ℝ}
    (model : BuhlmannStraubMomentModel sample weight theta hypotheticalMean
      hypotheticalVariance
      observation collectiveMean processVariance betweenVariance μ)
    (z : ℝ) (hweight : buhlmannStraubTotalWeight sample weight ≠ 0) :
    buhlmannStraubExpectedSqLoss sample weight theta hypotheticalMean observation
        collectiveMean z μ =
      (1 - z) ^ 2 * betweenVariance +
        z ^ 2 * processVariance / buhlmannStraubTotalWeight sample weight := by
  let riskMean := buhlmannStraubRiskMean theta hypotheticalMean
  let centeredRisk : Ω → ℝ := fun omega => riskMean omega - collectiveMean
  let total := buhlmannStraubWeightedResidualTotal sample weight theta
    hypotheticalMean observation
  let totalWeight := buhlmannStraubTotalWeight sample weight
  let processError : Ω → ℝ := fun omega => totalWeight⁻¹ * total omega
  have hCenteredMem : MemLp centeredRisk 2 μ :=
    model.riskMean_memLp.sub (memLp_const collectiveMean)
  have hTotalMem : MemLp total 2 μ := by
    unfold total buhlmannStraubWeightedResidualTotal
    exact memLp_finsetSum sample fun i hi =>
      (model.residual_memLp hi).const_mul (weight i)
  have hProcessMem : MemLp processError 2 μ :=
    hTotalMem.const_mul totalWeight⁻¹
  have hCenteredSq : Integrable (fun omega => (centeredRisk omega) ^ 2) μ := by
    refine (hCenteredMem.integrable_mul hCenteredMem).congr ?_
    exact Eventually.of_forall fun omega => by simp [Pi.mul_apply, pow_two]
  have hProcessSq : Integrable (fun omega => (processError omega) ^ 2) μ := by
    refine (hProcessMem.integrable_mul hProcessMem).congr ?_
    exact Eventually.of_forall fun omega => by simp [Pi.mul_apply, pow_two]
  have hCrossInt : Integrable (fun omega => centeredRisk omega * processError omega) μ :=
    hCenteredMem.integrable_mul hProcessMem
  have hMeanIdentity := buhlmannStraubWeightedMeanRv_sub_riskMean sample weight theta
    hypotheticalMean observation hweight
  have hProcessPoint :
      buhlmannStraubWeightedMeanRv sample weight observation - riskMean = processError := by
    have hleft :
        buhlmannStraubWeightedMeanRv sample weight observation - riskMean =
          fun omega => total omega / totalWeight := by
      simpa [riskMean, total, totalWeight] using hMeanIdentity
    refine hleft.trans ?_
    funext omega
    simp [processError, div_eq_inv_mul]
  have hProcessVariance :
      ∫ omega, (processError omega) ^ 2 ∂μ =
        processVariance / totalWeight := by
    calc
      ∫ omega, (processError omega) ^ 2 ∂μ =
          ∫ omega,
            (buhlmannStraubWeightedMeanRv sample weight observation omega -
              riskMean omega) ^ 2 ∂μ := by
        apply integral_congr_ae
        exact Eventually.of_forall fun omega => by
          have homega := congr_fun hProcessPoint omega
          simp only [Pi.sub_apply] at homega
          change processError omega ^ 2 =
            (buhlmannStraubWeightedMeanRv sample weight observation omega -
              riskMean omega) ^ 2
          rw [homega]
      _ = processVariance / totalWeight :=
        integral_sq_buhlmannStraubWeightedMeanRv_sub_riskMean model hweight
  have hCrossZero :
      ∫ omega, centeredRisk omega * processError omega ∂μ = 0 := by
    calc
      ∫ omega, centeredRisk omega * processError omega ∂μ =
          ∫ omega, totalWeight⁻¹ * (centeredRisk omega * total omega) ∂μ := by
        apply integral_congr_ae
        exact Eventually.of_forall fun omega => by
          simp [processError]
          ring
      _ = totalWeight⁻¹ *
          ∫ omega, centeredRisk omega * total omega ∂μ := by
        rw [integral_const_mul]
      _ = 0 := by
        rw [integral_buhlmannStraubRiskMean_mul_weightedResidual_eq_zero model]
        simp
  have hpoint :
      (fun omega =>
        (riskMean omega -
          buhlmannStraubPredictor sample weight observation collectiveMean z omega) ^ 2) =
      fun omega =>
        (1 - z) ^ 2 * (centeredRisk omega) ^ 2 +
          z ^ 2 * (processError omega) ^ 2 -
            (2 * z * (1 - z)) * (centeredRisk omega * processError omega) := by
    funext omega
    have homega := congr_fun hProcessPoint omega
    simp only [Pi.sub_apply] at homega
    unfold buhlmannStraubPredictor buhlmannStraubWeightedMeanRv
    change (riskMean omega -
      (collectiveMean + z *
        (buhlmannStraubWeightedMean sample weight
          (fun i => observation i omega) - collectiveMean))) ^ 2 = _
    have hmean : buhlmannStraubWeightedMean sample weight
        (fun i => observation i omega) - riskMean omega = processError omega := by
      simpa [buhlmannStraubWeightedMeanRv] using homega
    rw [show buhlmannStraubWeightedMean sample weight (fun i => observation i omega) =
      riskMean omega + processError omega by linarith]
    simp only [centeredRisk]
    ring
  have hfirst : Integrable
      (fun omega => (1 - z) ^ 2 * (centeredRisk omega) ^ 2) μ :=
    hCenteredSq.const_mul ((1 - z) ^ 2)
  have hsecond : Integrable
      (fun omega => z ^ 2 * (processError omega) ^ 2) μ :=
    hProcessSq.const_mul (z ^ 2)
  have hcross : Integrable
      (fun omega => (2 * z * (1 - z)) *
        (centeredRisk omega * processError omega)) μ :=
    hCrossInt.const_mul (2 * z * (1 - z))
  unfold buhlmannStraubExpectedSqLoss
  change ∫ omega,
    (riskMean omega -
      buhlmannStraubPredictor sample weight observation collectiveMean z omega) ^ 2 ∂μ = _
  rw [hpoint]
  calc
    ∫ omega,
        ((1 - z) ^ 2 * (centeredRisk omega) ^ 2 +
          z ^ 2 * (processError omega) ^ 2) -
            (2 * z * (1 - z)) *
              (centeredRisk omega * processError omega) ∂μ =
        (∫ omega,
          ((1 - z) ^ 2 * (centeredRisk omega) ^ 2 +
            z ^ 2 * (processError omega) ^ 2) ∂μ) -
          ∫ omega, (2 * z * (1 - z)) *
            (centeredRisk omega * processError omega) ∂μ :=
      integral_sub (hfirst.add hsecond) hcross
    _ = ((1 - z) ^ 2 * ∫ omega, (centeredRisk omega) ^ 2 ∂μ +
          z ^ 2 * ∫ omega, (processError omega) ^ 2 ∂μ) -
        (2 * z * (1 - z)) *
          ∫ omega, centeredRisk omega * processError omega ∂μ := by
      rw [integral_add hfirst hsecond, integral_const_mul, integral_const_mul,
        integral_const_mul]
    _ = (1 - z) ^ 2 * betweenVariance +
        z ^ 2 * processVariance / buhlmannStraubTotalWeight sample weight := by
      rw [model.latentVariance, hProcessVariance, hCrossZero]
      simp [totalWeight]
      ring

/-- Multiplying the true expected prediction loss by total exposure produces
the deterministic coefficient quadratic `P*w*(1-z)^2 + v*z^2`. -/
theorem buhlmannStraubExpectedSqLoss_scaled_eq_riskQuadratic
    [IsProbabilityMeasure μ]
    {sample : Finset ι} {weight : ι → ℝ}
    {theta : Ω → Θ} {hypotheticalMean hypotheticalVariance : Θ → ℝ}
    {observation : ι → Ω → ℝ}
    {collectiveMean processVariance betweenVariance : ℝ}
    (model : BuhlmannStraubMomentModel sample weight theta hypotheticalMean
      hypotheticalVariance
      observation collectiveMean processVariance betweenVariance μ)
    (z : ℝ) (hweight : buhlmannStraubTotalWeight sample weight ≠ 0) :
    buhlmannStraubTotalWeight sample weight *
        buhlmannStraubExpectedSqLoss sample weight theta hypotheticalMean observation
          collectiveMean z μ =
      buhlmannStraubRiskQuadratic (buhlmannStraubTotalWeight sample weight)
        processVariance betweenVariance z := by
  rw [buhlmannStraubExpectedSqLoss_eq model z hweight]
  unfold buhlmannStraubRiskQuadratic
  field_simp [hweight]

/-- Square completion of the coefficient-risk quadratic around the
Bühlmann-Straub credibility factor. -/
theorem buhlmannStraubRiskQuadratic_eq_at_credibility_add
    (totalWeight processVariance betweenVariance z : ℝ)
    (hden : processVariance + totalWeight * betweenVariance ≠ 0) :
    buhlmannStraubRiskQuadratic totalWeight processVariance betweenVariance z =
      buhlmannStraubRiskQuadratic totalWeight processVariance betweenVariance
        (buhlmannStraubCredibility totalWeight processVariance betweenVariance) +
      (processVariance + totalWeight * betweenVariance) *
        (z - buhlmannStraubCredibility totalWeight processVariance betweenVariance) ^ 2 := by
  unfold buhlmannStraubRiskQuadratic buhlmannStraubCredibility
  field_simp [hden]
  ring

/-- The source credibility factor minimizes the coefficient-risk quadratic
when its total quadratic coefficient is positive. -/
theorem buhlmannStraubCredibility_minimizes_riskQuadratic
    (totalWeight processVariance betweenVariance z : ℝ)
    (hpos : 0 < processVariance + totalWeight * betweenVariance) :
    buhlmannStraubRiskQuadratic totalWeight processVariance betweenVariance
        (buhlmannStraubCredibility totalWeight processVariance betweenVariance) ≤
      buhlmannStraubRiskQuadratic totalWeight processVariance betweenVariance z := by
  rw [buhlmannStraubRiskQuadratic_eq_at_credibility_add totalWeight processVariance
    betweenVariance z hpos.ne']
  exact le_add_of_nonneg_right (mul_nonneg hpos.le (sq_nonneg _))

/-- **Stochastic derivation of the credibility coefficient.** With positive
total exposure and positive total variance, the source credibility factor
minimizes the actual expected squared prediction loss over all scalar linear
credibility coefficients. -/
theorem buhlmannStraubCredibility_minimizes_expectedSqLoss
    [IsProbabilityMeasure μ]
    {sample : Finset ι} {weight : ι → ℝ}
    {theta : Ω → Θ} {hypotheticalMean hypotheticalVariance : Θ → ℝ}
    {observation : ι → Ω → ℝ}
    {collectiveMean processVariance betweenVariance : ℝ}
    (model : BuhlmannStraubMomentModel sample weight theta hypotheticalMean
      hypotheticalVariance
      observation collectiveMean processVariance betweenVariance μ)
    (z : ℝ)
    (hweight : 0 < buhlmannStraubTotalWeight sample weight)
    (hden : 0 < processVariance +
      buhlmannStraubTotalWeight sample weight * betweenVariance) :
    buhlmannStraubExpectedSqLoss sample weight theta hypotheticalMean observation
        collectiveMean
        (buhlmannStraubCredibility (buhlmannStraubTotalWeight sample weight)
          processVariance betweenVariance) μ ≤
      buhlmannStraubExpectedSqLoss sample weight theta hypotheticalMean observation
        collectiveMean z μ := by
  have hstar := buhlmannStraubExpectedSqLoss_scaled_eq_riskQuadratic model
    (buhlmannStraubCredibility (buhlmannStraubTotalWeight sample weight)
      processVariance betweenVariance) hweight.ne'
  have hz := buhlmannStraubExpectedSqLoss_scaled_eq_riskQuadratic model z hweight.ne'
  have hquad := buhlmannStraubCredibility_minimizes_riskQuadratic
    (buhlmannStraubTotalWeight sample weight) processVariance betweenVariance z hden
  rw [← hstar, ← hz] at hquad
  nlinarith

omit [MeasurableSpace Ω] in
/-- At the minimizing coefficient, the stochastic linear predictor is exactly
the deterministic estimate in the form of Bühlmann-Straub (1970), display
(4), p. 123. The source's empirical portfolio mean can be supplied as
`collectiveMean`. -/
theorem buhlmannStraubPredictor_credibility_eq_estimate
    (sample : Finset ι) (weight : ι → ℝ)
    (observation : ι → Ω → ℝ)
    (collectiveMean processVariance betweenVariance : ℝ)
    (hweight : buhlmannStraubTotalWeight sample weight ≠ 0)
    (hden : processVariance +
      buhlmannStraubTotalWeight sample weight * betweenVariance ≠ 0) :
    buhlmannStraubPredictor sample weight observation collectiveMean
        (buhlmannStraubCredibility (buhlmannStraubTotalWeight sample weight)
          processVariance betweenVariance) =
      fun omega => buhlmannStraubEstimate sample weight (fun i => observation i omega)
        collectiveMean processVariance betweenVariance := by
  funext omega
  have hform := buhlmannStraubEstimate_eq_credibility sample weight
    (fun i => observation i omega) collectiveMean processVariance betweenVariance
    hweight hden
  unfold buhlmannStraubPredictor buhlmannStraubWeightedMeanRv
  rw [hform]
  ring

end

end VerifiedReserving
