import VerifiedReserving.CDRMsep
import VerifiedReserving.ObservedData

/-!
# Calendar-year conditioning for the claims development result

Merz and Wüthrich (2008) condition on the triangle available after a calendar
diagonal: at time `t`, the observed cells in the modeled `n` by `n` square are
exactly those with `i + j ≤ t`.
The earlier CDR modules used the development-year filtration `D k`. This file
defines the source's calendar-year filtration and proves the corresponding
exact results from Mack's row-conditioned assumptions and accident-year
independence.

For row `i` and `k < n`, calendar time `i + k` contains exactly that row's
history through development year `k`, joined with observations from the other
rows. Independence therefore makes conditioning on the calendar triangle
equivalent to conditioning on row `i`'s own history. This gives the calendar-year
residual identity and its conditional second moment without adding a stochastic
assumption.
-/

open MeasureTheory Finset Filter ProbabilityTheory

namespace VerifiedReserving

noncomputable section

variable { Ω : Type* } [MeasurableSpace Ω] { μ : Measure Ω } { n : ℕ }

/-- Information after calendar diagonal `t`: the sigma-algebra generated by
all cells `C i j` with `i < n`, `j < n`, and `i + j ≤ t`. -/
@[implicit_reducible]
def RandomTriangle.calendarSigma (X : RandomTriangle Ω n) (t : ℕ) : MeasurableSpace Ω :=
  ⨆ i, ⨆ _ : i < n, ⨆ j, ⨆ _ : j < n, ⨆ _ : i + j ≤ t,
    MeasurableSpace.comap (X.C i j) inferInstance

/-- The calendar observations from rows other than `i`. -/
@[implicit_reducible]
def RandomTriangle.otherCalendar (X : RandomTriangle Ω n) (i t : ℕ) : MeasurableSpace Ω :=
  ⨆ i', ⨆ _ : i' ≠ i, ⨆ _ : i' < n, ⨆ j, ⨆ _ : j < n,
    ⨆ _ : i' + j ≤ t,
    MeasurableSpace.comap (X.C i' j) inferInstance

theorem RandomTriangle.calendarSigma_le (X : RandomTriangle Ω n) (t : ℕ) :
    X.calendarSigma t ≤ ‹MeasurableSpace Ω› :=
  iSup_le fun i => iSup_le fun _ => iSup_le fun j => iSup_le fun _ => iSup_le fun _ =>
    (X.measurable_C i j).comap_le

theorem RandomTriangle.calendarSigma_mono (X : RandomTriangle Ω n) :
    Monotone X.calendarSigma := by
  intro s t hst
  exact iSup_le fun i => iSup_le fun hi => iSup_le fun j => iSup_le fun hj =>
    iSup_le fun hij =>
    le_iSup_of_le i (le_iSup_of_le hi (le_iSup_of_le j
      (le_iSup_of_le hj (le_iSup_of_le (hij.trans hst) le_rfl))))

theorem RandomTriangle.stronglyMeasurable_calendarSigma_C
    (X : RandomTriangle Ω n) {i j t : ℕ} (hi : i < n) (hj : j < n)
    (hij : i + j ≤ t) :
    StronglyMeasurable[X.calendarSigma t] (X.C i j) := by
  have hlast : MeasurableSpace.comap (X.C i j) inferInstance ≤
      ⨆ _ : i + j ≤ t, MeasurableSpace.comap (X.C i j) inferInstance :=
    le_iSup (fun _ : i + j ≤ t => MeasurableSpace.comap (X.C i j) inferInstance) hij
  exact (Measurable.of_comap_le
    (le_iSup_of_le i (le_iSup_of_le hi (le_iSup_of_le j
      (le_iSup_of_le hj hlast))))).stronglyMeasurable

theorem RandomTriangle.rowSigma_mono (X : RandomTriangle Ω n) (i : ℕ) :
    Monotone (X.rowSigma i) := by
  intro s t hst
  exact iSup_le fun j => iSup_le fun hj =>
    le_iSup_of_le j (le_iSup_of_le (hj.trans hst) le_rfl)

theorem RandomTriangle.rowSigma_le_calendarSigma (X : RandomTriangle Ω n)
    {i : ℕ} (hi : i < n) {k : ℕ} (hk : k < n) :
    X.rowSigma i k ≤ X.calendarSigma (i + k) :=
  iSup_le fun j => iSup_le fun hj =>
    le_iSup_of_le i (le_iSup_of_le hi (le_iSup_of_le j
      (le_iSup_of_le (hj.trans_lt hk) (le_iSup_of_le (by omega) le_rfl))))

theorem RandomTriangle.otherCalendar_le_otherRowsAll (X : RandomTriangle Ω n)
    (i t : ℕ) : X.otherCalendar i t ≤ X.otherRowsAll i :=
  iSup_le fun i' => iSup_le fun hne => iSup_le fun _ => iSup_le fun j => iSup_le fun _ =>
    iSup_le fun _ =>
      (le_iSup (fun j => MeasurableSpace.comap (X.C i' j) inferInstance) j).trans
        (X.rowSigmaAll_le_otherRowsAll hne)

theorem RandomTriangle.otherCalendar_le (X : RandomTriangle Ω n) (i t : ℕ) :
    X.otherCalendar i t ≤ ‹MeasurableSpace Ω› :=
  (X.otherCalendar_le_otherRowsAll i t).trans (X.otherRowsAll_le i)

/-- For `k < n`, split the observed triangle at calendar time `i+k` into row
`i` through development `k` and all observations from the other rows. -/
theorem RandomTriangle.calendarSigma_eq_sup (X : RandomTriangle Ω n)
    {i k : ℕ} (hi : i < n) (hk : k < n) :
    X.calendarSigma (i + k) = X.rowSigma i k ⊔ X.otherCalendar i (i + k) := by
  refine le_antisymm ?_ (sup_le (X.rowSigma_le_calendarSigma hi hk) ?_)
  · refine iSup_le fun i' => iSup_le fun hi' => iSup_le fun j => iSup_le fun hj =>
      iSup_le fun hij => ?_
    by_cases h : i' = i
    · subst i'
      exact le_sup_of_le_left (le_iSup_of_le j (le_iSup_of_le (by omega) le_rfl))
    · exact le_sup_of_le_right (le_iSup_of_le i' (le_iSup_of_le h
        (le_iSup_of_le hi' (le_iSup_of_le j (le_iSup_of_le hj
          (le_iSup_of_le hij le_rfl))))))
  · exact iSup_le fun i' => iSup_le fun hne => iSup_le fun hi' =>
      iSup_le fun j => iSup_le fun hj => iSup_le fun hij =>
        le_iSup_of_le i' (le_iSup_of_le hi' (le_iSup_of_le j
          (le_iSup_of_le hj (le_iSup_of_le hij le_rfl))))

/-- Conditioning a function carried by row `i` on the calendar triangle at
time `i+k` is the same as conditioning on that row through development `k`. -/
theorem condExp_calendarSigma_eq_rowSigma [IsFiniteMeasure μ]
    (X : RandomTriangle Ω n) (hindep : RowsIndep X μ) {i : ℕ} (hi : i < n)
    {k : ℕ} (hk : k < n) {g : Ω → ℝ} (hg : StronglyMeasurable[X.rowSigmaAll i] g)
    (hgint : Integrable g μ) :
    μ[g | X.calendarSigma (i + k)] =ᵐ[μ] μ[g | X.rowSigma i k] := by
  rw [X.calendarSigma_eq_sup hi hk]
  exact condExp_sup_of_indep (X.rowSigma_le_rowSigmaAll i k) (X.rowSigmaAll_le i)
    (X.otherCalendar_le i (i + k))
    (indep_of_indep_of_le_right (indep_rowSigmaAll_otherRowsAll X hindep i)
      (X.otherCalendar_le_otherRowsAll i (i + k))) hg hgint

/-! ## Row-wise iteration -/

theorem condExp_C_rowSigma_succ [IsFiniteMeasure μ]
    (X : RandomTriangle Ω n) (f : ℕ → ℝ) (i d k : ℕ) (hi : i < n)
    (hdk : d ≤ k) (hrow : Mack1Row X μ f) :
    μ[X.C i (k + 1) | X.rowSigma i d]
      =ᵐ[μ] fun ω => f k * (μ[X.C i k | X.rowSigma i d]) ω := by
  have hle : X.rowSigma i d ≤ X.rowSigma i k := X.rowSigma_mono i hdk
  have h1 : μ[X.C i (k + 1) | X.rowSigma i d]
      =ᵐ[μ] μ[μ[X.C i (k + 1) | X.rowSigma i k] | X.rowSigma i d] :=
    (condExp_condExp_of_le hle (X.rowSigma_le i k)).symm
  have h2 : μ[μ[X.C i (k + 1) | X.rowSigma i k] | X.rowSigma i d]
      =ᵐ[μ] μ[(f k) • X.C i k | X.rowSigma i d] := by
    refine condExp_congr_ae ?_
    filter_upwards [hrow i hi k] with ω hω
    simp [Pi.smul_apply, hω]
  have h3 : μ[(f k) • X.C i k | X.rowSigma i d]
      =ᵐ[μ] (f k) • μ[X.C i k | X.rowSigma i d] :=
    condExp_smul (f k) (X.C i k) (X.rowSigma i d)
  refine h1.trans (h2.trans (h3.trans ?_))
  exact Eventually.of_forall fun ω => by simp [Pi.smul_apply]

theorem condExp_C_of_mack1Row_at [IsFiniteMeasure μ]
    (X : RandomTriangle Ω n) (f : ℕ → ℝ) (i d m : ℕ) (hi : i < n)
    (hrow : Mack1Row X μ f) (hint : ∀ j, Integrable (X.C i j) μ) :
    μ[X.C i (d + m) | X.rowSigma i d]
      =ᵐ[μ] fun ω => X.C i d ω * ∏ k ∈ Ico d (d + m), f k := by
  induction m with
  | zero =>
      have hmeas := X.stronglyMeasurable_rowSigma i (show d ≤ d from le_rfl)
      have h := condExp_of_stronglyMeasurable (X.rowSigma_le i d) hmeas (hint d)
      refine EventuallyEq.trans (EventuallyEq.of_eq h) ?_
      exact Eventually.of_forall fun ω => by simp
  | succ m ih =>
      have h := condExp_C_rowSigma_succ X f i d (d + m) hi
        (Nat.le_add_right d m) hrow
      rw [show d + (m + 1) = d + m + 1 from rfl]
      refine h.trans ?_
      filter_upwards [ih] with ω hω
      rw [hω, prod_Ico_succ_top (Nat.le_add_right d m)]
      ring

theorem condExp_C_calendar_of_rows [IsFiniteMeasure μ]
    (X : RandomTriangle Ω n) (f : ℕ → ℝ) (i d m : ℕ) (hi : i < n) (hd : d < n)
    (hindep : RowsIndep X μ) (hrow : Mack1Row X μ f)
    (hint : ∀ j, Integrable (X.C i j) μ) :
    μ[X.C i (d + m) | X.calendarSigma (i + d)]
      =ᵐ[μ] fun ω => X.C i d ω * ∏ k ∈ Ico d (d + m), f k :=
  (condExp_calendarSigma_eq_rowSigma X hindep hi hd
      (X.stronglyMeasurable_rowSigmaAll i (d + m)) (hint (d + m))).trans
    (condExp_C_of_mack1Row_at X f i d m hi hrow hint)

/-! ## Exact calendar-year CDR -/

/-- The true CDR over calendar step `t → t+1`, defined from successive
conditional expectations of the same ultimate claim. -/
def RandomTriangle.calendarTrueCDR (X : RandomTriangle Ω n) (μ : Measure Ω)
    (i t : ℕ) : Ω → ℝ :=
  μ[X.C i (n - 1) | X.calendarSigma t]
    - μ[X.C i (n - 1) | X.calendarSigma (t + 1)]

/-- The true calendar-year CDR is a martingale difference. As in the
development-year version, mathlib's conditional expectation is zero outside
the integrable case, so the statement has its probabilistic meaning when the
ultimate is integrable. -/
theorem condExp_calendarTrueCDR_eq_zero [IsFiniteMeasure μ]
    (X : RandomTriangle Ω n) (i t : ℕ) :
    μ[X.calendarTrueCDR μ i t | X.calendarSigma t] =ᵐ[μ] 0 := by
  have hsub : μ[X.calendarTrueCDR μ i t | X.calendarSigma t]
      =ᵐ[μ] μ[μ[X.C i (n - 1) | X.calendarSigma t] | X.calendarSigma t]
        - μ[μ[X.C i (n - 1) | X.calendarSigma (t + 1)] | X.calendarSigma t] :=
    condExp_sub integrable_condExp integrable_condExp _
  have h1 : μ[μ[X.C i (n - 1) | X.calendarSigma t] | X.calendarSigma t]
      =ᵐ[μ] μ[X.C i (n - 1) | X.calendarSigma t] :=
    condExp_condExp_of_le le_rfl (X.calendarSigma_le t)
  have h2 : μ[μ[X.C i (n - 1) | X.calendarSigma (t + 1)] | X.calendarSigma t]
      =ᵐ[μ] μ[X.C i (n - 1) | X.calendarSigma t] :=
    condExp_condExp_of_le (X.calendarSigma_mono (Nat.le_succ t))
      (X.calendarSigma_le (t + 1))
  filter_upwards [hsub, h1, h2] with ω hs hω1 hω2
  rw [hs, Pi.sub_apply, hω1, hω2, sub_self, Pi.zero_apply]

/-- Under Mack's row-conditioned mean assumption and independent rows, the
calendar CDR at time `i+k` is the remaining development product times the
new one-step residual. -/
theorem calendarTrueCDR_eq_of_rows [IsFiniteMeasure μ]
    (X : RandomTriangle Ω n) (f : ℕ → ℝ) (i k : ℕ)
    (hi : i < n) (hk : k < n - 1) (hindep : RowsIndep X μ)
    (hrow : Mack1Row X μ f) (hint : ∀ j, Integrable (X.C i j) μ) :
    X.calendarTrueCDR μ i (i + k)
      =ᵐ[μ] fun ω =>
        (∏ j ∈ Ico (k + 1) (n - 1), f j) * (f k * X.C i k ω - X.C i (k + 1) ω) := by
  have h1 := condExp_C_calendar_of_rows X f i k (n - 1 - k) hi (by omega)
    hindep hrow hint
  have h2 := condExp_C_calendar_of_rows X f i (k + 1) (n - 1 - (k + 1))
    hi (by omega) hindep hrow hint
  have hk1 : k + (n - 1 - k) = n - 1 := by omega
  have hk2 : k + 1 + (n - 1 - (k + 1)) = n - 1 := by omega
  rw [hk1] at h1
  rw [hk2, show i + (k + 1) = i + k + 1 by omega] at h2
  filter_upwards [h1, h2] with ω hω1 hω2
  simp only [RandomTriangle.calendarTrueCDR, Pi.sub_apply]
  rw [hω1, hω2, Finset.prod_eq_prod_Ico_succ_bot hk f]
  ring

/-- The exact conditional second moment of the calendar-year true CDR. This
is the calendar-filtration counterpart of `condExp_sq_trueCDR`. -/
theorem condExp_sq_calendarTrueCDR_of_rows [IsFiniteMeasure μ]
    (X : RandomTriangle Ω n) (f σ2 : ℕ → ℝ) (i k : ℕ)
    (hi : i < n) (hk : k < n - 1) (hindep : RowsIndep X μ)
    (hrow1 : Mack1Row X μ f) (hrow3 : Mack3Row X μ f σ2)
    (hint : ∀ j, Integrable (X.C i j) μ)
    (hε2 : Integrable (fun ω => (X.eps f i k ω) ^ 2) μ) :
    μ[fun ω => (X.calendarTrueCDR μ i (i + k) ω) ^ 2 | X.calendarSigma (i + k)]
      =ᵐ[μ] fun ω => cdrProcVar (X.C i k ω) f σ2 (n - 1) k := by
  have hCDR := calendarTrueCDR_eq_of_rows X f i k hi hk hindep hrow1 hint
  have hsq : (fun ω => (X.calendarTrueCDR μ i (i + k) ω) ^ 2)
      =ᵐ[μ] ((∏ j ∈ Ico (k + 1) (n - 1), f j) ^ 2) •
        fun ω => (X.eps f i k ω) ^ 2 := by
    filter_upwards [hCDR] with ω hω
    simp only [Pi.smul_apply, smul_eq_mul, RandomTriangle.eps, hω]
    ring
  have hvar : μ[fun ω => (X.eps f i k ω) ^ 2 | X.calendarSigma (i + k)]
      =ᵐ[μ] fun ω => σ2 k * X.C i k ω :=
    (condExp_calendarSigma_eq_rowSigma X hindep hi (by omega)
      ((X.stronglyMeasurable_eps_rowSigmaAll f i k).pow 2) hε2).trans
      (hrow3 i hi k)
  refine (condExp_congr_ae hsq).trans ((condExp_smul _ _ _).trans ?_)
  filter_upwards [hvar] with ω hω
  simp only [Pi.smul_apply, smul_eq_mul, hω, cdrProcVar]

/-- The calendar-year conditional second moment read as a conditional
variance. The mean-zero theorem removes the squared conditional mean. -/
theorem condVar_calendarTrueCDR_of_rows [IsFiniteMeasure μ]
    (X : RandomTriangle Ω n) (f σ2 : ℕ → ℝ) (i k : ℕ)
    (hi : i < n) (hk : k < n - 1) (hindep : RowsIndep X μ)
    (hrow1 : Mack1Row X μ f) (hrow3 : Mack3Row X μ f σ2)
    (hint : ∀ j, Integrable (X.C i j) μ)
    (hε2 : Integrable (fun ω => (X.eps f i k ω) ^ 2) μ) :
    (fun ω =>
        (μ[fun ω => (X.calendarTrueCDR μ i (i + k) ω) ^ 2 |
          X.calendarSigma (i + k)]) ω
          - ((μ[X.calendarTrueCDR μ i (i + k) | X.calendarSigma (i + k)]) ω) ^ 2)
      =ᵐ[μ] fun ω => cdrProcVar (X.C i k ω) f σ2 (n - 1) k := by
  filter_upwards [condExp_sq_calendarTrueCDR_of_rows X f σ2 i k hi hk hindep
      hrow1 hrow3 hint hε2,
    condExp_calendarTrueCDR_eq_zero (μ := μ) X i (i + k)] with ω h1 h2
  simp [h1, h2]

end

end VerifiedReserving
