import VerifiedReserving.Variance

/-!
# From independence across accident years to the `D_k` form of the assumptions

Mack (1993) states his assumptions on a single accident year: for accident
year `i`, conditionally on that year's own history `C_{i,0}, …, C_{i,k}`,

(M1row)  `E[C_{i,k+1} | σ(C_{i,0}, …, C_{i,k})] = f_k C_{i,k}`,
(M3row)  `E[(C_{i,k+1} - f_k C_{i,k})² | σ(C_{i,0}, …, C_{i,k})] = σ_k² C_{i,k}`,

and separately assumes (M2), that the accident years are independent.  Every
theorem in the library instead uses the `D_k`-conditioned forms `Mack1` and
`Mack3`, where `D_k` is the σ-algebra of everything observed up to
development year `k`, all accident years together.  Mack's papers pass from
the first form to the second in one sentence.  This file proves the passage.

The mathematical content is a general fact about conditional expectation:
enlarging the conditioning σ-algebra by an independent one changes nothing.
If `m₁ ≤ m₁'`, `f` is `m₁'`-measurable and `m₂` is independent of `m₁'`, then

`E[f | m₁ ⊔ m₂] = E[f | m₁]`.

Mathlib has the special case `m₁ = ⊥` (`condExp_indep_eq`: conditioning on an
independent σ-algebra returns the mean).  The join version is proved here by
the characterisation of conditional expectation, testing on the π-system of
rectangles `a ∩ b` with `a ∈ m₁` and `b ∈ m₂`; on such a rectangle both
integrals factor, by `condExp_indep_eq` applied to the indicator `1_a f`.

Applied with `m₁ = ` row `i` up to development year `k`, `m₁' = ` all of row
`i`, and `m₂ = ` the other rows up to `k`, this turns (M1row) into (M1) and
(M3row) into (M3), given the hypothesis `RowsGenerateD` that `D_k` is
generated by the rows' histories up to `k` (which is what `D_k` means) and
the hypothesis `RowsIndep` that the rows are independent (Mack's (M2)).
-/

open MeasureTheory Finset Filter ProbabilityTheory

namespace VerifiedReserving

noncomputable section

/-! ## Conditioning on an independent enlargement -/

section CondExpSup

variable {Ω : Type*} {m₁ m₁' m₂ m0 : MeasurableSpace Ω} {μ : Measure Ω}

/-- With `m₁'` independent of `m₂`, an integral of an `m₁'`-measurable
function over a rectangle `a ∩ b` factors: `∫_{a ∩ b} F = μ(b) ∫_a F`. -/
theorem setIntegral_inter_of_indep [IsFiniteMeasure μ]
    (hle₁' : m₁' ≤ m0) (hle₂ : m₂ ≤ m0) (hindep : Indep m₁' m₂ μ)
    {F : Ω → ℝ} (hF : StronglyMeasurable[m₁'] F) (hFint : Integrable F μ)
    {a b : Set Ω} (ha : MeasurableSet[m₁'] a) (hb : MeasurableSet[m₂] b) :
    ∫ ω in a ∩ b, F ω ∂μ = μ.real b * ∫ ω in a, F ω ∂μ := by
  have ha0 : MeasurableSet[m0] a := hle₁' _ ha
  have hG : StronglyMeasurable[m₁'] (a.indicator F) := hF.indicator ha
  have hGint : Integrable (a.indicator F) μ := hFint.indicator ha0
  have hcond : μ[a.indicator F | m₂] =ᵐ[μ] fun _ => ∫ ω, a.indicator F ω ∂μ :=
    condExp_indep_eq hle₁' hle₂ hG hindep
  calc ∫ ω in a ∩ b, F ω ∂μ
      = ∫ ω in b, a.indicator F ω ∂μ := by
        rw [setIntegral_indicator ha0, Set.inter_comm]
    _ = ∫ ω in b, (μ[a.indicator F | m₂]) ω ∂μ := (setIntegral_condExp hle₂ hGint hb).symm
    _ = ∫ _ω in b, (∫ ω, a.indicator F ω ∂μ) ∂μ := by
        refine setIntegral_congr_ae (hle₂ _ hb) ?_
        filter_upwards [hcond] with ω hω _ using hω
    _ = μ.real b * ∫ ω, a.indicator F ω ∂μ := by rw [setIntegral_const, smul_eq_mul]
    _ = μ.real b * ∫ ω in a, F ω ∂μ := by rw [integral_indicator ha0]

/-- **Conditioning on an independent enlargement changes nothing.**
If `f` is measurable for `m₁'`, the σ-algebra `m₂` is independent of `m₁'`,
and `m₁ ≤ m₁'`, then `E[f | m₁ ⊔ m₂] = E[f | m₁]` almost surely.

This is the lemma behind Mack's passage from a row-conditioned assumption to
the same statement conditioned on the whole observed triangle. -/
theorem condExp_sup_of_indep [IsFiniteMeasure μ]
    (h₁₁' : m₁ ≤ m₁') (hle₁' : m₁' ≤ m0) (hle₂ : m₂ ≤ m0) (hindep : Indep m₁' m₂ μ)
    {f : Ω → ℝ} (hfm : StronglyMeasurable[m₁'] f) (hfint : Integrable f μ) :
    μ[f | m₁ ⊔ m₂] =ᵐ[μ] μ[f | m₁] := by
  have hle₁ : m₁ ≤ m0 := h₁₁'.trans hle₁'
  have hsup : m₁ ⊔ m₂ ≤ m0 := sup_le hle₁ hle₂
  -- the π-system of rectangles generates the join
  set R : Set (Set Ω) := {t | ∃ a b, MeasurableSet[m₁] a ∧ MeasurableSet[m₂] b ∧ t = a ∩ b}
    with hR
  have hgen : m₁ ⊔ m₂ = MeasurableSpace.generateFrom R := by
    refine le_antisymm (sup_le ?_ ?_) (MeasurableSpace.generateFrom_le ?_)
    · intro t ht
      exact MeasurableSpace.measurableSet_generateFrom
        ⟨t, Set.univ, ht, MeasurableSet.univ, (Set.inter_univ t).symm⟩
    · intro t ht
      exact MeasurableSpace.measurableSet_generateFrom
        ⟨Set.univ, t, MeasurableSet.univ, ht, (Set.univ_inter t).symm⟩
    · rintro t ⟨a, b, ha, hb, rfl⟩
      exact MeasurableSet.inter ((le_sup_left : m₁ ≤ m₁ ⊔ m₂) _ ha)
        ((le_sup_right : m₂ ≤ m₁ ⊔ m₂) _ hb)
  have hpi : IsPiSystem R := by
    rintro s ⟨a, b, ha, hb, rfl⟩ t ⟨c, d, hc, hd, rfl⟩ -
    refine ⟨a ∩ c, b ∩ d, ha.inter hc, hb.inter hd, ?_⟩
    ext ω; simp only [Set.mem_inter_iff]; tauto
  have hgm : StronglyMeasurable[m₁] (μ[f | m₁]) := stronglyMeasurable_condExp
  have hgint : Integrable (μ[f | m₁]) μ := integrable_condExp
  -- the two set integrals agree on every set of the join
  have hint_eq : ∀ t, MeasurableSet[m₁ ⊔ m₂] t →
      ∫ ω in t, (μ[f | m₁]) ω ∂μ = ∫ ω in t, f ω ∂μ := by
    refine MeasurableSpace.induction_on_inter
      (C := fun t _ => ∫ ω in t, (μ[f | m₁]) ω ∂μ = ∫ ω in t, f ω ∂μ) hgen hpi ?_ ?_ ?_ ?_
    · simp
    · rintro t ⟨a, b, ha, hb, rfl⟩
      rw [setIntegral_inter_of_indep hle₁' hle₂ hindep (hgm.mono h₁₁') hgint (h₁₁' _ ha) hb,
        setIntegral_inter_of_indep hle₁' hle₂ hindep hfm hfint (h₁₁' _ ha) hb,
        setIntegral_condExp hle₁ hfint ha]
    · intro t htm ih
      have ht0 : MeasurableSet[m0] t := hsup _ htm
      have e1 := integral_add_compl ht0 hgint
      have e2 := integral_add_compl ht0 hfint
      have e3 : ∫ ω, (μ[f | m₁]) ω ∂μ = ∫ ω, f ω ∂μ := integral_condExp hle₁
      linarith
    · intro s hdisj hsm ih
      rw [integral_iUnion (fun i => hsup _ (hsm i)) hdisj hgint.integrableOn,
        integral_iUnion (fun i => hsup _ (hsm i)) hdisj hfint.integrableOn]
      exact tsum_congr ih
  exact (ae_eq_condExp_of_forall_setIntegral_eq hsup hfint
    (fun s _ _ => integrable_condExp.integrableOn) (fun s hs _ => hint_eq s hs)
    ((hgm.mono (le_sup_left : m₁ ≤ m₁ ⊔ m₂)).aestronglyMeasurable)).symm

end CondExpSup

/-! ## The row σ-algebras of a random triangle -/

variable {Ω : Type*} [MeasurableSpace Ω] {μ : Measure Ω} {n : ℕ}

/-- Every entry of the triangle is measurable for the ambient σ-algebra. -/
theorem RandomTriangle.measurable_C (X : RandomTriangle Ω n) (i j : ℕ) :
    Measurable (X.C i j) :=
  ((X.meas i j j le_rfl).mono (X.D_le j)).measurable

/-- The σ-algebra generated by accident year `i`'s own history up to
development year `k`: what Mack conditions on in his row-wise assumptions. -/
@[implicit_reducible]
def RandomTriangle.rowSigma (X : RandomTriangle Ω n) (i k : ℕ) : MeasurableSpace Ω :=
  ⨆ j, ⨆ _ : j ≤ k, MeasurableSpace.comap (X.C i j) inferInstance

/-- The σ-algebra generated by the whole of accident year `i`. -/
@[implicit_reducible]
def RandomTriangle.rowSigmaAll (X : RandomTriangle Ω n) (i : ℕ) : MeasurableSpace Ω :=
  ⨆ j, MeasurableSpace.comap (X.C i j) inferInstance

/-- The σ-algebra generated by the other accident years' histories up to
development year `k`. -/
@[implicit_reducible]
def RandomTriangle.otherRowsSigma (X : RandomTriangle Ω n) (i k : ℕ) : MeasurableSpace Ω :=
  ⨆ i', ⨆ _ : i' ≠ i, X.rowSigma i' k

/-- The σ-algebra generated by the other accident years in full. -/
@[implicit_reducible]
def RandomTriangle.otherRowsAll (X : RandomTriangle Ω n) (i : ℕ) : MeasurableSpace Ω :=
  ⨆ i', ⨆ _ : i' ≠ i, X.rowSigmaAll i'

theorem RandomTriangle.rowSigma_le_rowSigmaAll (X : RandomTriangle Ω n) (i k : ℕ) :
    X.rowSigma i k ≤ X.rowSigmaAll i :=
  iSup_le fun j => iSup_le fun _ =>
    le_iSup (fun j => MeasurableSpace.comap (X.C i j) inferInstance) j

theorem RandomTriangle.rowSigmaAll_le (X : RandomTriangle Ω n) (i : ℕ) :
    X.rowSigmaAll i ≤ ‹MeasurableSpace Ω› :=
  iSup_le fun j => (X.measurable_C i j).comap_le

theorem RandomTriangle.rowSigma_le (X : RandomTriangle Ω n) (i k : ℕ) :
    X.rowSigma i k ≤ ‹MeasurableSpace Ω› :=
  (X.rowSigma_le_rowSigmaAll i k).trans (X.rowSigmaAll_le i)

theorem RandomTriangle.otherRowsSigma_le (X : RandomTriangle Ω n) (i k : ℕ) :
    X.otherRowsSigma i k ≤ ‹MeasurableSpace Ω› :=
  iSup_le fun i' => iSup_le fun _ => X.rowSigma_le i' k

theorem RandomTriangle.otherRowsAll_le (X : RandomTriangle Ω n) (i : ℕ) :
    X.otherRowsAll i ≤ ‹MeasurableSpace Ω› :=
  iSup_le fun i' => iSup_le fun _ => X.rowSigmaAll_le i'

theorem RandomTriangle.otherRowsSigma_le_otherRowsAll (X : RandomTriangle Ω n) (i k : ℕ) :
    X.otherRowsSigma i k ≤ X.otherRowsAll i :=
  iSup_le fun i' => iSup_le fun hne =>
    (X.rowSigma_le_rowSigmaAll i' k).trans
      (le_iSup₂ (f := fun i' (_ : i' ≠ i) => X.rowSigmaAll i') i' hne)

theorem RandomTriangle.rowSigmaAll_le_otherRowsAll (X : RandomTriangle Ω n) {i j : ℕ}
    (hne : j ≠ i) : X.rowSigmaAll j ≤ X.otherRowsAll i :=
  le_iSup₂ (f := fun i' (_ : i' ≠ i) => X.rowSigmaAll i') j hne

/-- Every entry of row `i` is measurable for the row's σ-algebra. -/
theorem RandomTriangle.stronglyMeasurable_rowSigmaAll (X : RandomTriangle Ω n) (i j : ℕ) :
    StronglyMeasurable[X.rowSigmaAll i] (X.C i j) :=
  (Measurable.of_comap_le
    (le_iSup (fun j => MeasurableSpace.comap (X.C i j) inferInstance) j)).stronglyMeasurable

/-- An entry of row `i` observed by development year `k` is measurable for the
row's history up to `k`. -/
theorem RandomTriangle.stronglyMeasurable_rowSigma (X : RandomTriangle Ω n) (i : ℕ) {j k : ℕ}
    (hjk : j ≤ k) : StronglyMeasurable[X.rowSigma i k] (X.C i j) :=
  (Measurable.of_comap_le
    (le_iSup₂ (f := fun j (_ : j ≤ k) => MeasurableSpace.comap (X.C i j) inferInstance) j
      hjk)).stronglyMeasurable

/-- The one-step residual of row `i` is measurable for the row's σ-algebra. -/
theorem RandomTriangle.stronglyMeasurable_eps_rowSigmaAll (X : RandomTriangle Ω n)
    (f : ℕ → ℝ) (i k : ℕ) : StronglyMeasurable[X.rowSigmaAll i] (X.eps f i k) :=
  (X.stronglyMeasurable_rowSigmaAll i (k + 1)).sub
    (stronglyMeasurable_const.mul (X.stronglyMeasurable_rowSigmaAll i k))

/-! ## Mack's (M2) and the row-conditioned assumptions -/

/-- **Mack's assumption (M2).** The accident years are mutually independent:
the σ-algebras generated by the individual rows are independent. -/
def RowsIndep (X : RandomTriangle Ω n) (μ : Measure Ω) : Prop :=
  iIndep (fun i => X.rowSigmaAll i) μ

/-- The observed-data filtration is what its name says: `D k` is generated by
the accident years' histories up to development year `k`. -/
def RowsGenerateD (X : RandomTriangle Ω n) : Prop :=
  ∀ k, X.D k = ⨆ i, X.rowSigma i k

/-- Mack's first assumption as he states it, conditioned on the accident
year's own history: `E[C_{i,k+1} | C_{i,0}, …, C_{i,k}] = f_k C_{i,k}`. -/
def Mack1Row (X : RandomTriangle Ω n) (μ : Measure Ω) (f : ℕ → ℝ) : Prop :=
  ∀ i, i < n → ∀ k, μ[X.C i (k + 1) | X.rowSigma i k] =ᵐ[μ] fun ω => f k * X.C i k ω

/-- Mack's third assumption as he states it, conditioned on the accident
year's own history. -/
def Mack3Row (X : RandomTriangle Ω n) (μ : Measure Ω) (f : ℕ → ℝ) (σ2 : ℕ → ℝ) : Prop :=
  ∀ i, i < n → ∀ k,
    μ[fun ω => (X.eps f i k ω) ^ 2 | X.rowSigma i k] =ᵐ[μ] fun ω => σ2 k * X.C i k ω

/-- Under (M2), an accident year is independent of all the others together. -/
theorem indep_rowSigmaAll_otherRowsAll (X : RandomTriangle Ω n)
    (hindep : RowsIndep X μ) (i : ℕ) :
    Indep (X.rowSigmaAll i) (X.otherRowsAll i) μ := by
  have h := indep_iSup_of_disjoint (m := fun i' => X.rowSigmaAll i')
    (fun i' => X.rowSigmaAll_le i') hindep (S := ({i} : Set ℕ)) (T := ({i}ᶜ : Set ℕ))
    disjoint_compl_right
  rw [show (⨆ i' ∈ ({i} : Set ℕ), X.rowSigmaAll i') = X.rowSigmaAll i by simp] at h
  refine indep_of_indep_of_le_right h (iSup_le fun i' => iSup_le fun hne => ?_)
  exact le_iSup₂ (f := fun i' (_ : i' ∈ ({i}ᶜ : Set ℕ)) => X.rowSigmaAll i') i'
    (Set.mem_compl_singleton_iff.mpr hne)

/-- Under (M2), a row is independent of the other rows' observed histories. -/
theorem indep_rowSigmaAll_otherRowsSigma (X : RandomTriangle Ω n)
    (hindep : RowsIndep X μ) (i k : ℕ) :
    Indep (X.rowSigmaAll i) (X.otherRowsSigma i k) μ :=
  indep_of_indep_of_le_right (indep_rowSigmaAll_otherRowsAll X hindep i)
    (X.otherRowsSigma_le_otherRowsAll i k)

/-- The observed-data σ-algebra splits as row `i` joined with the other rows. -/
theorem RandomTriangle.D_eq_sup (X : RandomTriangle Ω n) (hgen : RowsGenerateD X) (i k : ℕ) :
    X.D k = X.rowSigma i k ⊔ X.otherRowsSigma i k := by
  rw [hgen k]
  exact iSup_split_single _ i

/-! ## The passage -/

/-- **Mack's (M1) from his row-conditioned assumption.** If the accident
years are independent (M2) and the observed-data filtration is generated by
their histories, then the row-conditioned assumption (M1row) implies the
`D_k`-conditioned assumption (M1) used by every theorem in this library.

This is the step Mack takes in one sentence. -/
theorem mack1_of_mack1Row [IsFiniteMeasure μ] (X : RandomTriangle Ω n) (f : ℕ → ℝ)
    (hgen : RowsGenerateD X) (hindep : RowsIndep X μ) (hrow : Mack1Row X μ f)
    (hint : ∀ i k, Integrable (X.C i k) μ) : Mack1 X μ f := by
  intro i hi k
  rw [X.D_eq_sup hgen i k]
  refine EventuallyEq.trans ?_ (hrow i hi k)
  exact condExp_sup_of_indep (X.rowSigma_le_rowSigmaAll i k) (X.rowSigmaAll_le i)
    (X.otherRowsSigma_le i k) (indep_rowSigmaAll_otherRowsSigma X hindep i k)
    (X.stronglyMeasurable_rowSigmaAll i (k + 1)) (hint i (k + 1))

/-- **Mack's (M3) from his row-conditioned assumption**, by the same
argument applied to the squared residual. -/
theorem mack3_of_mack3Row [IsFiniteMeasure μ] (X : RandomTriangle Ω n) (f : ℕ → ℝ) (σ2 : ℕ → ℝ)
    (hgen : RowsGenerateD X) (hindep : RowsIndep X μ) (hrow : Mack3Row X μ f σ2)
    (hint : ∀ i k, Integrable (fun ω => (X.eps f i k ω) ^ 2) μ) : Mack3 X μ f σ2 := by
  intro i hi k
  rw [X.D_eq_sup hgen i k]
  refine EventuallyEq.trans ?_ (hrow i hi k)
  exact condExp_sup_of_indep (X.rowSigma_le_rowSigmaAll i k) (X.rowSigmaAll_le i)
    (X.otherRowsSigma_le i k) (indep_rowSigmaAll_otherRowsSigma X hindep i k)
    (((X.stronglyMeasurable_eps_rowSigmaAll f i k).pow 2)) (hint i k)

/-- Under (M1row), a row's one-step residual has conditional mean zero given
that row's own history. -/
theorem condExp_eps_rowSigma [IsFiniteMeasure μ] (X : RandomTriangle Ω n) (f : ℕ → ℝ)
    (hrow : Mack1Row X μ f) {i : ℕ} (hi : i < n) (k : ℕ)
    (hint : ∀ j, Integrable (X.C i j) μ) :
    μ[X.eps f i k | X.rowSigma i k] =ᵐ[μ] fun _ => (0 : ℝ) := by
  have hg : Integrable (fun ω => f k * X.C i k ω) μ := (hint k).const_mul (f k)
  have h1 : μ[X.eps f i k | X.rowSigma i k]
      =ᵐ[μ] μ[X.C i (k + 1) | X.rowSigma i k] - μ[fun ω => f k * X.C i k ω | X.rowSigma i k] :=
    condExp_sub (hint (k + 1)) hg _
  have h2 : μ[fun ω => f k * X.C i k ω | X.rowSigma i k] = fun ω => f k * X.C i k ω :=
    condExp_of_stronglyMeasurable (X.rowSigma_le i k)
      (stronglyMeasurable_const.mul (X.stronglyMeasurable_rowSigma i le_rfl)) hg
  filter_upwards [h1, hrow i hi k] with ω hω hω'
  rw [hω, Pi.sub_apply, hω', h2]
  ring

/-- **Mack's (M2') from independence across accident years.** The
conditional uncorrelatedness of residuals from different accident years,
which `Variance.lean` and `SigmaUnbiased.lean` take as an assumption, is not
an extra assumption: it follows from (M2) and the row-conditioned (M1row).

The argument conditions on the observed data together with the whole of the
other accident year: the other year's residual comes out of the conditional
expectation, what is left is the conditional mean of row `i`'s residual given
a σ-algebra that adds nothing about row `i`, which is zero by (M1row); the
tower property brings the statement back down to `D_k`. -/
theorem mack2'_of_rows [IsFiniteMeasure μ] (X : RandomTriangle Ω n) (f : ℕ → ℝ)
    (hgen : RowsGenerateD X) (hindep : RowsIndep X μ) (hrow : Mack1Row X μ f)
    (hint : ∀ i j, Integrable (X.C i j) μ)
    (hprod : ∀ i j k, Integrable (fun ω => X.eps f i k ω * X.eps f j k ω) μ) :
    Mack2' X μ f := by
  have hepsint : ∀ i k, Integrable (X.eps f i k) μ := fun i k =>
    (hint i (k + 1)).sub ((hint i k).const_mul (f k))
  intro k i hi j hj hij
  have hi' : i < n := lt_of_mem_contributors hi
  have hm₂le : X.otherRowsSigma i k ⊔ X.rowSigmaAll j ≤ ‹MeasurableSpace Ω› :=
    sup_le (X.otherRowsSigma_le i k) (X.rowSigmaAll_le j)
  have hDle : X.D k ≤ X.rowSigma i k ⊔ (X.otherRowsSigma i k ⊔ X.rowSigmaAll j) := by
    rw [X.D_eq_sup hgen i k, ← sup_assoc]
    exact le_sup_left
  have hindep' : Indep (X.rowSigmaAll i) (X.otherRowsSigma i k ⊔ X.rowSigmaAll j) μ :=
    indep_of_indep_of_le_right (indep_rowSigmaAll_otherRowsAll X hindep i)
      (sup_le (X.otherRowsSigma_le_otherRowsAll i k)
        (X.rowSigmaAll_le_otherRowsAll (Ne.symm hij)))
  -- row `j`'s residual comes out of the enlarged conditional expectation
  have hstepA : μ[X.eps f j k * X.eps f i k |
        X.rowSigma i k ⊔ (X.otherRowsSigma i k ⊔ X.rowSigmaAll j)]
      =ᵐ[μ] X.eps f j k *
        μ[X.eps f i k | X.rowSigma i k ⊔ (X.otherRowsSigma i k ⊔ X.rowSigmaAll j)] :=
    condExp_mul_of_stronglyMeasurable_left
      ((X.stronglyMeasurable_eps_rowSigmaAll f j k).mono
        ((le_sup_right : X.rowSigmaAll j ≤ X.otherRowsSigma i k ⊔ X.rowSigmaAll j).trans
          le_sup_right))
      (hprod j i k) (hepsint i k)
  -- and the enlargement says nothing about row `i`
  have hstepB : μ[X.eps f i k | X.rowSigma i k ⊔ (X.otherRowsSigma i k ⊔ X.rowSigmaAll j)]
      =ᵐ[μ] μ[X.eps f i k | X.rowSigma i k] :=
    condExp_sup_of_indep (X.rowSigma_le_rowSigmaAll i k) (X.rowSigmaAll_le i) hm₂le hindep'
      (X.stronglyMeasurable_eps_rowSigmaAll f i k) (hepsint i k)
  have hstepC := condExp_eps_rowSigma X f hrow hi' k (fun j => hint i j)
  have hzero : μ[X.eps f j k * X.eps f i k |
      X.rowSigma i k ⊔ (X.otherRowsSigma i k ⊔ X.rowSigmaAll j)] =ᵐ[μ] (0 : Ω → ℝ) := by
    filter_upwards [hstepA, hstepB, hstepC] with ω h1 h2 h3
    rw [h1, Pi.mul_apply, h2, h3]
    simp
  have hcomm : (fun ω => X.eps f i k ω * X.eps f j k ω) = X.eps f j k * X.eps f i k := by
    ext ω; exact mul_comm _ _
  rw [hcomm]
  refine (condExp_condExp_of_le hDle (sup_le (X.rowSigma_le i k) hm₂le)).symm.trans ?_
  refine (condExp_congr_ae hzero).trans ?_
  rw [condExp_zero]
  rfl

end

end VerifiedReserving
