import Mathlib.Probability.Moments.Variance
import Mathlib.Probability.ConditionalExpectation
import VerifiedReserving.ODP

/-!
# The stochastic over-dispersed Poisson layer

Renshaw and Verrall, *A stochastic model underlying the chain-ladder
technique*, British Actuarial Journal 4 (1998) 903-923, introduced the model.
England and Verrall (1999), equations (2.5)-(2.7), restate its independent
incremental-claims assumptions as

`E[X_{i,k}] = m_{i,k}`, `Var(X_{i,k}) = phi * m_{i,k}`, and
`log m_{i,k} = c + alpha_i + beta_k`, with positive dispersion and the
corner constraints `alpha_0 = beta_0 = 0`.

England and Verrall, *Analytic and bootstrap estimates of prediction errors in
claims reserving*, Insurance: Mathematics and Economics 25 (1999) 281-293,
equations (3.1)-(3.5), and England and Verrall, *Stochastic claims reserving in
general insurance*, British Actuarial Journal 8 (2002) 443-518, equations
(7.1)-(7.9), split prediction error into process and estimation components.
The single-cell GLM formula uses a delta-method approximation for the
estimation variance. This file therefore proves the exact probability identity
under explicit independence and unbiasedness hypotheses, while recording the
delta-method formula as `glmCellMsep` and `glmAggregateMsep` definitions.

The residual bootstrap follows England and Verrall (1999), equations
(4.2)-(4.4), and England and Verrall (2002), equations (8.1) and the following
display. `englandVerrallBootstrapMean` and
`englandVerrallPredictiveReserve` are definitions of the two stages. They make
no theorem claiming coverage, consistency or statistical validity. In
particular, the process simulator is an input because the first two ODP moments
do not select a unique predictive distribution.
-/

open MeasureTheory Finset Filter ProbabilityTheory

namespace VerifiedReserving

noncomputable section

variable {Omega : Type*} [MeasurableSpace Omega] {mu : Measure Omega} {n : Nat}

/-! ## Incremental ODP model and exact conditional moments -/

/-- A cell of an `n` by `n` incremental claims square. The observed and future
triangles are finite subsets of this type. -/
abbrev ODPCell (n : Nat) := Fin n × Fin n

/-- The positive log-link mean `exp(c + alpha_i + beta_k)`. -/
def logLinkFit (c : Real) (alpha beta : Nat -> Real) (i k : Nat) : Real :=
  Real.exp (c + alpha i + beta k)

/-- A mean surface has the source's corner-constrained log-link form on the
modeled finite square. -/
def ODPLogLink (m : Nat -> Nat -> Real) (n : Nat) : Prop :=
  ∃ (c : Real) (alpha beta : Nat -> Real),
    alpha 0 = 0 ∧ beta 0 = 0 ∧
      ∀ p : ODPCell n, m p.1 p.2 = logLinkFit c alpha beta p.1 p.2

/-- The random incremental claim in a finite cell. -/
def odpCellRv (X : Nat -> Nat -> Omega -> Real) (p : ODPCell n) : Omega -> Real :=
  X p.1 p.2

/-- Renshaw-Verrall's stochastic ODP assumptions: positive dispersion, a
positive corner-constrained log-link mean, measurable square-integrable
incremental cells with variance `phi * m`, and mutual independence. The model
is stated on the full finite square; a run-off triangle is a finite subset
selected below. -/
structure ODPModel (X : Nat -> Nat -> Omega -> Real) (mu : Measure Omega)
    (m : Nat -> Nat -> Real) (phi : Real) (n : Nat) : Prop where
  phi_pos : 0 < phi
  log_link : ODPLogLink m n
  measurable : forall p : ODPCell n, Measurable (odpCellRv X p)
  memLp_two : forall p : ODPCell n, MemLp (odpCellRv X p) 2 mu
  mean_eq : forall p : ODPCell n, (∫ omega, odpCellRv X p omega ∂mu) = m p.1 p.2
  variance_eq : forall p : ODPCell n,
    variance (odpCellRv X p) mu = phi * m p.1 p.2
  independent : iIndepFun (fun p : ODPCell n => odpCellRv X p) mu

/-- Every modeled mean is positive because it has a log-link representation. -/
theorem ODPModel.mean_pos {X : Nat -> Nat -> Omega -> Real} {m : Nat -> Nat -> Real}
    {phi : Real} (h : ODPModel X mu m phi n) (p : ODPCell n) : 0 < m p.1 p.2 := by
  rcases h.log_link with ⟨c, alpha, beta, _, _, hm⟩
  rw [hm p]
  exact Real.exp_pos _

/-- The sigma-algebra generated by one incremental cell. -/
@[reducible] def odpCellSigma (X : Nat -> Nat -> Omega -> Real) (p : ODPCell n) :
    MeasurableSpace Omega :=
  MeasurableSpace.comap (odpCellRv X p) inferInstance

/-- The vector of incremental claims in a finite collection of cells. -/
def odpObservedRv (X : Nat -> Nat -> Omega -> Real) (s : Finset (ODPCell n))
    (omega : Omega) : s -> Real :=
  fun p => odpCellRv X (p : ODPCell n) omega

/-- The sigma-algebra generated by a finite collection of incremental cells. -/
@[reducible] def odpObservedSigma (X : Nat -> Nat -> Omega -> Real)
    (s : Finset (ODPCell n)) :
    MeasurableSpace Omega :=
  MeasurableSpace.comap (odpObservedRv X s) inferInstance

/-- A cell's generated sigma-algebra is contained in the ambient one. -/
theorem odpCellSigma_le {X : Nat -> Nat -> Omega -> Real} {m : Nat -> Nat -> Real}
    {phi : Real} (h : ODPModel X mu m phi n) (p : ODPCell n) :
    odpCellSigma X p <= (inferInstance : MeasurableSpace Omega) :=
  (h.measurable p).comap_le

/-- The sigma-algebra generated by finitely many cells is contained in the
ambient one. -/
theorem odpObservedSigma_le {X : Nat -> Nat -> Omega -> Real}
    {m : Nat -> Nat -> Real} {phi : Real} (h : ODPModel X mu m phi n)
    (s : Finset (ODPCell n)) :
    odpObservedSigma X s <= (inferInstance : MeasurableSpace Omega) := by
  apply Measurable.comap_le
  exact measurable_pi_lambda _ fun p => by
    simpa [odpObservedRv] using h.measurable (p : ODPCell n)

/-- A cell not in the observed set is independent of the vector of observed
cells. This is the finite-data form of the source's independent-incremental
assumption. -/
theorem odpIndep_cell_observed {X : Nat -> Nat -> Omega -> Real}
    {m : Nat -> Nat -> Real} {phi : Real} (h : ODPModel X mu m phi n)
    (p : ODPCell n) (s : Finset (ODPCell n)) (hp : p ∉ s) :
    Indep (odpCellSigma X p) (odpObservedSigma X s) mu := by
  have hdis : Disjoint ({p} : Finset (ODPCell n)) s := by
    simp [hp]
  have hfin := h.independent.indepFun_finset ({p} : Finset (ODPCell n)) s hdis
    h.measurable
  let ps : ({p} : Finset (ODPCell n)) := ⟨p, by simp⟩
  have hcomp := hfin.comp (measurable_pi_apply ps) measurable_id
  rw [IndepFun_iff_Indep] at hcomp
  change Indep
    (MeasurableSpace.comap (fun omega => X p.1 p.2 omega) Real.measurableSpace)
    (MeasurableSpace.comap (fun omega (q : s) => X q.1.1 q.1.2 omega)
      MeasurableSpace.pi) mu
  simpa [odpCellRv, Function.comp_def, ps] using hcomp

/-- Under the ODP model, a future cell conditioned on any disjoint finite set
of observed cells has conditional mean `m_{i,k}`. This is an exact conditional
moment statement, not a GLM approximation. -/
theorem condExp_odpCell_given_observed [IsProbabilityMeasure mu]
    {X : Nat -> Nat -> Omega -> Real} {m : Nat -> Nat -> Real} {phi : Real}
    (h : ODPModel X mu m phi n) (p : ODPCell n) (s : Finset (ODPCell n))
    (hp : p ∉ s) :
    mu[odpCellRv X p | odpObservedSigma X s] =ᵐ[mu]
      fun _ => m p.1 p.2 := by
  have hmeas : StronglyMeasurable[odpCellSigma X p] (odpCellRv X p) :=
    (Measurable.of_comap_le le_rfl).stronglyMeasurable
  have hcond := condExp_indep_eq (odpCellSigma_le h p) (odpObservedSigma_le h s)
    hmeas (odpIndep_cell_observed h p s hp)
  simpa only [h.mean_eq p] using hcond

/-- The corresponding exact conditional second central moment is
`phi * m_{i,k}`. This is the conditional version of Renshaw-Verrall's ODP
variance assumption. -/
theorem condExp_sq_odpCell_sub_given_observed [IsProbabilityMeasure mu]
    {X : Nat -> Nat -> Omega -> Real} {m : Nat -> Nat -> Real} {phi : Real}
    (h : ODPModel X mu m phi n) (p : ODPCell n) (s : Finset (ODPCell n))
    (hp : p ∉ s) :
    mu[fun omega => (odpCellRv X p omega - m p.1 p.2) ^ 2 |
      odpObservedSigma X s] =ᵐ[mu] fun _ => phi * m p.1 p.2 := by
  have hmeas : StronglyMeasurable[odpCellSigma X p]
      (fun omega => (odpCellRv X p omega - m p.1 p.2) ^ 2) :=
    (((Measurable.of_comap_le le_rfl).sub measurable_const).pow_const 2).stronglyMeasurable
  have hcond := condExp_indep_eq (odpCellSigma_le h p) (odpObservedSigma_le h s)
    hmeas (odpIndep_cell_observed h p s hp)
  have hint : (∫ omega, (odpCellRv X p omega - m p.1 p.2) ^ 2 ∂mu) =
      phi * m p.1 p.2 := by
    rw [← h.variance_eq p, variance_eq_integral (h.measurable p).aemeasurable,
      h.mean_eq p]
  simpa [hint] using hcond

/-! ## Exact prediction-error decomposition -/

/-- The random aggregate over a finite set of incremental cells. -/
def odpAggregate (X : Nat -> Nat -> Omega -> Real) (s : Finset (ODPCell n)) :
    Omega -> Real :=
  ∑ p ∈ s, odpCellRv X p

/-- The mean of an ODP aggregate is the sum of its cell means. -/
theorem integral_odpAggregate [IsProbabilityMeasure mu]
    {X : Nat -> Nat -> Omega -> Real} {m : Nat -> Nat -> Real} {phi : Real}
    (h : ODPModel X mu m phi n) (s : Finset (ODPCell n)) :
    (∫ omega, odpAggregate X s omega ∂mu) = ∑ p ∈ s, m p.1 p.2 := by
  change (∫ omega, (∑ p ∈ s, odpCellRv X p) omega ∂mu) = _
  calc
    _ = ∑ p ∈ s, ∫ omega, odpCellRv X p omega ∂mu := by
      simpa only [Finset.sum_apply] using
        (integral_finsetSum s (fun p _ => (h.memLp_two p).integrable one_le_two))
    _ = _ := Finset.sum_congr rfl fun p _ => h.mean_eq p

/-- Independent ODP cells make the aggregate process variance the sum of the
cell process variances, `phi * sum m`. This is the first term of England and
Verrall (2002), equations (7.8)-(7.9). -/
theorem variance_odpAggregate [IsProbabilityMeasure mu]
    {X : Nat -> Nat -> Omega -> Real} {m : Nat -> Nat -> Real} {phi : Real}
    (h : ODPModel X mu m phi n) (s : Finset (ODPCell n)) :
    variance (odpAggregate X s) mu = phi * ∑ p ∈ s, m p.1 p.2 := by
  have hv := IndepFun.variance_sum
    (s := s) (X := fun p : ODPCell n => odpCellRv X p)
    (fun p _ => h.memLp_two p)
    (fun p hp q hq hpq => h.independent.indepFun hpq)
  change variance (∑ p ∈ s, odpCellRv X p) mu = _
  simpa [h.variance_eq, Finset.mul_sum] using hv

/-- Mean squared prediction error for a random target and random predictor. -/
def meanSquaredPredictionError (Y Yhat : Omega -> Real) (mu : Measure Omega) : Real :=
  ∫ omega, (Y omega - Yhat omega) ^ 2 ∂mu

/-- Exact process-plus-estimation decomposition. If the predictor is unbiased
for the same mean as the future target and is independent of it, the MSEP is
the sum of their variances. England and Verrall (1999), equation (3.1), writes
this as an approximation because its fitted GLM predictor then receives a
delta-method variance approximation. -/
theorem meanSquaredPredictionError_eq_variance_add [IsProbabilityMeasure mu]
    {Y Yhat : Omega -> Real} (hY : MemLp Y 2 mu) (hYhat : MemLp Yhat 2 mu)
    (hmean : (∫ omega, Y omega ∂mu) = ∫ omega, Yhat omega ∂mu)
    (hindep : IndepFun Y Yhat mu) :
    meanSquaredPredictionError Y Yhat mu = variance Y mu + variance Yhat mu := by
  have hzero : (∫ omega, Y omega - Yhat omega ∂mu) = 0 := by
    rw [integral_sub (hY.integrable one_le_two) (hYhat.integrable one_le_two),
      hmean, sub_self]
  have hzero' : (∫ omega, (Y - Yhat) omega ∂mu) = 0 := by simpa using hzero
  change (∫ omega, ((Y - Yhat) omega) ^ 2 ∂mu) = _
  calc
    _ = variance (Y - Yhat) mu :=
      (variance_of_integral_eq_zero (hY.aemeasurable.sub hYhat.aemeasurable) hzero').symm
    _ = variance Y mu + variance Yhat mu := by
      rw [variance_sub hY hYhat, hindep.covariance_eq_zero hY hYhat]
      ring

/-- Exact aggregate ODP prediction error under an unbiased predictor that is
independent of future process outcomes. The source's GLM calculation replaces
the final predictor variance by the delta-method covariance formula below. -/
theorem odpAggregateMsep_eq [IsProbabilityMeasure mu]
    {X : Nat -> Nat -> Omega -> Real} {m : Nat -> Nat -> Real} {phi : Real}
    (h : ODPModel X mu m phi n) (s : Finset (ODPCell n)) (Yhat : Omega -> Real)
    (hYhat : MemLp Yhat 2 mu)
    (hmean : (∫ omega, Yhat omega ∂mu) = ∑ p ∈ s, m p.1 p.2)
    (hindep : IndepFun (odpAggregate X s) Yhat mu) :
    meanSquaredPredictionError (odpAggregate X s) Yhat mu =
      phi * ∑ p ∈ s, m p.1 p.2 + variance Yhat mu := by
  have hagg : MemLp (odpAggregate X s) 2 mu := by
    exact memLp_finsetSum' s (fun p _ => h.memLp_two p)
  rw [meanSquaredPredictionError_eq_variance_add hagg hYhat
    ((integral_odpAggregate h s).trans hmean.symm) hindep,
    variance_odpAggregate h s]

/-! ## The GLM formulas, kept at their source status -/

/-- England and Verrall (2002), equation (7.7): the single-cell ODP GLM MSEP
approximation `phi * mhat + mhat^2 * Var(etahat)`. This is a definition because
the second term comes from a Taylor expansion of `exp(etahat)`. -/
def glmCellMsep (phi mhat etaVariance : Real) : Real :=
  phi * mhat + mhat ^ 2 * etaVariance

/-- Delta-method estimation variance of an aggregate. `etaCov p q` is the
covariance of the two fitted linear predictors. -/
def glmAggregateEstimationVariance {iota : Type*} (s : Finset iota)
    (mhat : iota -> Real) (etaCov : iota -> iota -> Real) : Real :=
  ∑ p ∈ s, ∑ q ∈ s, mhat p * mhat q * etaCov p q

/-- England and Verrall (2002), equations (7.8)-(7.9), in covariance-matrix
form: summed ODP process variance plus the delta-method covariance quadratic
form. This remains an approximation definition. -/
def glmAggregateMsep {iota : Type*} (phi : Real) (s : Finset iota)
    (mhat : iota -> Real) (etaCov : iota -> iota -> Real) : Real :=
  phi * ∑ p ∈ s, mhat p + glmAggregateEstimationVariance s mhat etaCov

/-- The covariance-matrix aggregate definition reduces on one cell to equation
(7.7), taking the diagonal covariance as the linear-predictor variance. -/
theorem glmAggregateMsep_singleton {iota : Type*} [DecidableEq iota]
    (phi : Real) (p : iota) (mhat : iota -> Real) (etaCov : iota -> iota -> Real) :
    glmAggregateMsep phi {p} mhat etaCov = glmCellMsep phi (mhat p) (etaCov p p) := by
  simp [glmAggregateMsep, glmAggregateEstimationVariance, glmCellMsep, pow_two]

/-! ## Multiplicative and log-link parametrizations -/

/-- Every log-link fit is a multiplicative fit. -/
theorem logLinkFit_eq_multFit (c : Real) (alpha beta : Nat -> Real) (i k : Nat) :
    logLinkFit c alpha beta i k =
      multFit (fun j => Real.exp (c + alpha j)) (fun l => Real.exp (beta l)) i k := by
  simp [logLinkFit, multFit, Real.exp_add]

/-- Corner row effects for a positive multiplicative model. -/
def cornerRow (a : Nat -> Real) (i : Nat) : Real := Real.log (a i) - Real.log (a 0)

/-- Corner column effects for a positive multiplicative model. -/
def cornerColumn (b : Nat -> Real) (k : Nat) : Real := Real.log (b k) - Real.log (b 0)

/-- The row corner constraint is automatic. -/
theorem cornerRow_zero (a : Nat -> Real) : cornerRow a 0 = 0 := by
  simp [cornerRow]

/-- The column corner constraint is automatic. -/
theorem cornerColumn_zero (b : Nat -> Real) : cornerColumn b 0 = 0 := by
  simp [cornerColumn]

/-- Conversely, positive multiplicative means have the corner-constrained
log-link representation described by England and Verrall (2002), Section
2.3.4: `alpha_0 = beta_0 = 0`. -/
theorem logLinkFit_corner_eq_multFit (a b : Nat -> Real)
    (ha : forall i, 0 < a i) (hb : forall k, 0 < b k) (i k : Nat) :
    logLinkFit (Real.log (a 0) + Real.log (b 0)) (cornerRow a) (cornerColumn b) i k =
      multFit a b i k := by
  rw [logLinkFit, multFit]
  have harg : Real.log (a 0) + Real.log (b 0) + cornerRow a i + cornerColumn b k =
      Real.log (a i) + Real.log (b k) := by
    simp only [cornerRow, cornerColumn]
    ring
  rw [harg, Real.exp_add, Real.exp_log (ha i), Real.exp_log (hb k)]

/-! ## England-Verrall residual bootstrap definitions -/

/-- Unscaled Pearson residual, England and Verrall (1999), equation (4.2), and
England and Verrall (2002), equation (8.1). -/
def pearsonResidual (claim fitted : Real) : Real :=
  (claim - fitted) / Real.sqrt fitted

/-- Pearson dispersion estimate, England and Verrall (1999), equation (4.4).
The real denominator exposes the source's required positive degrees of
freedom rather than using truncated natural subtraction. -/
def pearsonScale {iota : Type*} (s : Finset iota) (residual : iota -> Real)
    (parameterCount : Nat) : Real :=
  (∑ p ∈ s, residual p ^ 2) / ((s.card : Real) - parameterCount)

/-- The degrees-of-freedom adjustment suggested by England (2002), equation
(3.1), applied to an unscaled Pearson residual. -/
def adjustedPearsonResidual (sampleCount parameterCount : Nat) (r : Real) : Real :=
  Real.sqrt ((sampleCount : Real) / ((sampleCount : Real) - parameterCount)) * r

/-- Invert a Pearson residual to form a pseudo-incremental observation,
England and Verrall (1999), equation (4.3), and England and Verrall (2002),
the display after equation (8.1). -/
def bootstrapIncremental (fitted resampledResidual : Real) : Real :=
  resampledResidual * Real.sqrt fitted + fitted

/-- Inverting a Pearson residual and recomputing it returns the resampled
residual when the fitted mean is positive. -/
theorem pearsonResidual_bootstrapIncremental (fitted r : Real) (hfitted : 0 < fitted) :
    pearsonResidual (bootstrapIncremental fitted r) fitted = r := by
  rw [pearsonResidual, bootstrapIncremental]
  have hs : Real.sqrt fitted ≠ 0 := ne_of_gt (Real.sqrt_pos.2 hfitted)
  field_simp
  ring

/-- Forming pseudo-data from the original Pearson residual recovers the
original claim when the fitted mean is positive. -/
theorem bootstrapIncremental_pearsonResidual (claim fitted : Real) (hfitted : 0 < fitted) :
    bootstrapIncremental fitted (pearsonResidual claim fitted) = claim := by
  rw [bootstrapIncremental, pearsonResidual]
  have hs : Real.sqrt fitted ≠ 0 := ne_of_gt (Real.sqrt_pos.2 hfitted)
  field_simp
  ring

/-- One England-Verrall bootstrap refit. `draw` samples residual indices with
replacement and `refit` maps the pseudo past triangle to fitted means in the
future triangle. This is an algorithmic definition, not a validity claim. -/
def englandVerrallBootstrapMean {past future : Type*}
    (fitted residual : past -> Real) (draw : past -> past)
    (refit : (past -> Real) -> future -> Real) : future -> Real :=
  refit (fun p => bootstrapIncremental (fitted p) (residual (draw p)))

/-- England's two-stage predictive reserve definition. `processDraw` supplies
a simulated future incremental conditional on each bootstrap mean. The ODP
moment equations do not determine that simulator's distribution. -/
def englandVerrallPredictiveReserve {past future outcome : Type*}
    (futureCells : Finset future) (fitted residual : past -> Real) (draw : past -> past)
    (refit : (past -> Real) -> future -> Real)
    (processDraw : (future -> Real) -> future -> outcome -> Real)
    (omega : outcome) : Real :=
  ∑ q ∈ futureCells,
    processDraw (englandVerrallBootstrapMean fitted residual draw refit) q omega

end

end VerifiedReserving
