import Mathlib
import VerifiedReserving.ChainLadder

/-!
# Mack's model: the stochastic layer (first theorem)

Mack (1993) works with a random run-off triangle `C i k : Ω → ℝ` and the
σ-algebras `D k` generated by the first `k+1` development years of every
accident year. His first assumption, stated conditionally on the row's own
history and combined with independence across accident years, gives

(M1)  `E[C_{i,k+1} | D_k] = f_k C_{i,k}`   a.s., for every `i` and `k`.

This file states (M1) in exactly that `D_k`-conditioned form and proves the
first half of Mack's Theorem 2: the chain-ladder factor `f̂_k` is
conditionally unbiased, `E[f̂_k | D_k] = f_k`, on the event `S_k ≠ 0`.
The argument is Mack's: `f̂_k = S_k⁻¹ ∑_i C_{i,k+1}`, the factor `S_k⁻¹` is
`D_k`-measurable and comes out of the conditional expectation, and (M1)
turns the remaining sum into `f_k S_k`.

Independence across accident years (M2) is not used here; it is what
justifies passing from Mack's row-conditioned assumption to the
`D_k`-conditioned form, and that passage is `Independence.lean`.
-/

open MeasureTheory Finset Filter

namespace VerifiedReserving

noncomputable section

/-- A random run-off triangle with `n` accident and development years,
together with the filtration `D k` of "everything observed up to development
year `k`". -/
structure RandomTriangle (Ω : Type*) [MeasurableSpace Ω] (n : ℕ) where
  /-- cumulative claims of accident year `i` at development year `k` -/
  C : ℕ → ℕ → Ω → ℝ
  /-- the σ-algebra generated by development years `0, …, k` (all accident years) -/
  D : ℕ → MeasurableSpace Ω
  D_le : ∀ k, D k ≤ ‹MeasurableSpace Ω›
  /-- the `D k` form a filtration -/
  D_mono : Monotone D
  /-- `C i j` is `D k`-measurable as soon as `j ≤ k` -/
  meas : ∀ i j k, j ≤ k → StronglyMeasurable[D k] (C i j)

variable {Ω : Type*} [MeasurableSpace Ω] {μ : Measure Ω} {n : ℕ}

/-- The pointwise (deterministic) triangle seen at outcome `ω`. -/
def RandomTriangle.at (X : RandomTriangle Ω n) (ω : Ω) : ℕ → ℕ → ℝ :=
  fun i k => X.C i k ω

/-- Mack's first assumption in the `D_k`-conditioned form:
`E[C_{i,k+1} | D_k] = f_k C_{i,k}` almost surely. -/
def Mack1 (X : RandomTriangle Ω n) (μ : Measure Ω) (f : ℕ → ℝ) : Prop :=
  ∀ i, i < n → ∀ k, μ[X.C i (k + 1) | X.D k] =ᵐ[μ] fun ω => f k * X.C i k ω

/-- The column sum `S_k` as a random variable. -/
def RandomTriangle.Srv (X : RandomTriangle Ω n) (k : ℕ) : Ω → ℝ :=
  fun ω => S (X.at ω) n k

/-- The chain-ladder factor `f̂_k` as a random variable. -/
def RandomTriangle.fhatRv (X : RandomTriangle Ω n) (k : ℕ) : Ω → ℝ :=
  fun ω => fhat (X.at ω) n k

theorem RandomTriangle.Srv_eq_sum (X : RandomTriangle Ω n) (k : ℕ) :
    X.Srv k = ∑ i ∈ contributors n k, X.C i k := by
  ext ω
  simp [RandomTriangle.Srv, S, RandomTriangle.at, Finset.sum_apply]

theorem RandomTriangle.fhatRv_eq (X : RandomTriangle Ω n) (k : ℕ) :
    X.fhatRv k = (fun ω => (X.Srv k ω)⁻¹) * ∑ i ∈ contributors n k, X.C i (k + 1) := by
  ext ω
  simp [RandomTriangle.fhatRv, RandomTriangle.Srv, RandomTriangle.at, fhat, T, S,
    Finset.sum_apply, div_eq_inv_mul]

/-- `S_k` is `D_k`-measurable. -/
theorem RandomTriangle.stronglyMeasurable_Srv (X : RandomTriangle Ω n) (k : ℕ) :
    StronglyMeasurable[X.D k] (X.Srv k) := by
  rw [X.Srv_eq_sum]
  exact Finset.stronglyMeasurable_sum _ (fun i _ => X.meas i k k le_rfl)

/-- **Mack (1993), Theorem 2, first part.** Under (M1), on the event
`S_k ≠ 0`, the chain-ladder factor is conditionally unbiased:
`E[f̂_k | D_k] = f_k`. -/
theorem condExp_fhatRv (X : RandomTriangle Ω n) (f : ℕ → ℝ) (k : ℕ)
    (hM : Mack1 X μ f)
    (hS : ∀ᵐ ω ∂μ, X.Srv k ω ≠ 0)
    (hCint : ∀ i ∈ contributors n k, Integrable (X.C i (k + 1)) μ)
    (hfint : Integrable (X.fhatRv k) μ) :
    μ[X.fhatRv k | X.D k] =ᵐ[μ] fun _ => f k := by
  -- the numerator as a random variable
  set Tk : Ω → ℝ := ∑ i ∈ contributors n k, X.C i (k + 1) with hTk
  have hTint : Integrable Tk μ :=
    (integrable_finsetSum _ hCint).congr
      (Eventually.of_forall fun ω => (Finset.sum_apply ω _ _).symm)
  have hinv : StronglyMeasurable[X.D k] (fun ω => (X.Srv k ω)⁻¹) :=
    ((X.stronglyMeasurable_Srv k).measurable.inv).stronglyMeasurable
  have hprod : Integrable ((fun ω => (X.Srv k ω)⁻¹) * Tk) μ := by
    rw [← X.fhatRv_eq]; exact hfint
  -- pull the `D_k`-measurable factor out
  have h1 : μ[X.fhatRv k | X.D k] =ᵐ[μ] (fun ω => (X.Srv k ω)⁻¹) * μ[Tk | X.D k] := by
    rw [X.fhatRv_eq]
    exact condExp_mul_of_stronglyMeasurable_left hinv hprod hTint
  -- (M1) evaluates the conditional expectation of the numerator
  have h2 : μ[Tk | X.D k] =ᵐ[μ] fun ω => f k * X.Srv k ω := by
    have hsum := condExp_finsetSum hCint (m := X.D k)
    have hall : ∀ᵐ ω ∂μ, ∀ i ∈ contributors n k,
        μ[X.C i (k + 1) | X.D k] ω = f k * X.C i k ω := by
      rw [eventually_all_finset]
      intro i hi
      exact hM i (lt_of_mem_contributors hi) k
    refine hsum.trans ?_
    filter_upwards [hall] with ω hω
    rw [Finset.sum_apply, Finset.sum_congr rfl (fun i hi => hω i hi), X.Srv_eq_sum,
      Finset.sum_apply, Finset.mul_sum]
  -- assemble
  refine h1.trans ?_
  filter_upwards [h2, hS] with ω hω hSω
  simp only [Pi.mul_apply, hω]
  field_simp

/-- `f̂_j` is `D_k`-measurable once development year `j+1` is observed. -/
theorem RandomTriangle.stronglyMeasurable_fhatRv (X : RandomTriangle Ω n) (j k : ℕ)
    (hjk : j + 1 ≤ k) : StronglyMeasurable[X.D k] (X.fhatRv j) := by
  rw [X.fhatRv_eq]
  refine StronglyMeasurable.mul ?_ ?_
  · exact ((((X.stronglyMeasurable_Srv j).mono (X.D_mono (Nat.le_of_succ_le hjk))).measurable).inv).stronglyMeasurable
  · exact Finset.stronglyMeasurable_sum _ (fun i _ => X.meas i (j + 1) k hjk)

/-- **Mack (1993), Theorem 2, second part (conditional form).** Under (M1),
for development years `j < k`, `E[f̂_j f̂_k | D_j] = f_j f_k`. -/
theorem condExp_fhatRv_mul [IsFiniteMeasure μ] (X : RandomTriangle Ω n) (f : ℕ → ℝ)
    (j k : ℕ) (hjk : j + 1 ≤ k)
    (hM : Mack1 X μ f)
    (hSj : ∀ᵐ ω ∂μ, X.Srv j ω ≠ 0) (hSk : ∀ᵐ ω ∂μ, X.Srv k ω ≠ 0)
    (hCj : ∀ i ∈ contributors n j, Integrable (X.C i (j + 1)) μ)
    (hCk : ∀ i ∈ contributors n k, Integrable (X.C i (k + 1)) μ)
    (hfj : Integrable (X.fhatRv j) μ) (hfk : Integrable (X.fhatRv k) μ)
    (hprod : Integrable (X.fhatRv j * X.fhatRv k) μ) :
    μ[X.fhatRv j * X.fhatRv k | X.D j] =ᵐ[μ] fun _ => f j * f k := by
  have hle : X.D j ≤ X.D k := X.D_mono (Nat.le_of_succ_le hjk)
  -- condition on `D_k` first: `f̂_j` comes out, `f̂_k` becomes `f_k`
  have h1 : μ[X.fhatRv j * X.fhatRv k | X.D k] =ᵐ[μ] X.fhatRv j * μ[X.fhatRv k | X.D k] :=
    condExp_mul_of_stronglyMeasurable_left (X.stronglyMeasurable_fhatRv j k hjk) hprod hfk
  have h2 : X.fhatRv j * μ[X.fhatRv k | X.D k] =ᵐ[μ] (f k) • X.fhatRv j := by
    filter_upwards [condExp_fhatRv X f k hM hSk hCk hfk] with ω hω
    simp [Pi.mul_apply, Pi.smul_apply, hω, mul_comm]
  -- tower property down to `D_j`
  have h3 : μ[X.fhatRv j * X.fhatRv k | X.D j]
      =ᵐ[μ] μ[μ[X.fhatRv j * X.fhatRv k | X.D k] | X.D j] :=
    (condExp_condExp_of_le hle (X.D_le k)).symm
  have h4 : μ[μ[X.fhatRv j * X.fhatRv k | X.D k] | X.D j] =ᵐ[μ] μ[(f k) • X.fhatRv j | X.D j] :=
    condExp_congr_ae (h1.trans h2)
  have h5 : μ[(f k) • X.fhatRv j | X.D j] =ᵐ[μ] (f k) • μ[X.fhatRv j | X.D j] :=
    condExp_smul (f k) (X.fhatRv j) (X.D j)
  have h6 := condExp_fhatRv X f j hM hSj hCj hfj
  refine h3.trans (h4.trans (h5.trans ?_))
  filter_upwards [h6] with ω hω
  simp [Pi.smul_apply, hω, mul_comm]

/-- **Mack (1993), Theorem 2, second part.** Under (M1) and on a probability
space, `E[f̂_j f̂_k] = f_j f_k` for `j < k`; together with `E[f̂_k] = f_k`
this says the development factors are uncorrelated. -/
theorem integral_fhatRv_mul [IsProbabilityMeasure μ] (X : RandomTriangle Ω n) (f : ℕ → ℝ)
    (j k : ℕ) (hjk : j + 1 ≤ k) (hM : Mack1 X μ f)
    (hSj : ∀ᵐ ω ∂μ, X.Srv j ω ≠ 0) (hSk : ∀ᵐ ω ∂μ, X.Srv k ω ≠ 0)
    (hCj : ∀ i ∈ contributors n j, Integrable (X.C i (j + 1)) μ)
    (hCk : ∀ i ∈ contributors n k, Integrable (X.C i (k + 1)) μ)
    (hfj : Integrable (X.fhatRv j) μ) (hfk : Integrable (X.fhatRv k) μ)
    (hprod : Integrable (X.fhatRv j * X.fhatRv k) μ) :
    ∫ ω, X.fhatRv j ω * X.fhatRv k ω ∂μ = f j * f k := by
  have h := condExp_fhatRv_mul X f j k hjk hM hSj hSk hCj hCk hfj hfk hprod
  have hint : ∫ ω, X.fhatRv j ω * X.fhatRv k ω ∂μ
      = ∫ ω, (μ[X.fhatRv j * X.fhatRv k | X.D j]) ω ∂μ :=
    (integral_condExp (X.D_le j)).symm
  rw [hint, integral_congr_ae h]
  simp

/-- `E[f̂_k] = f_k` on a probability space (Mack 1993, Theorem 2, first part,
unconditional form). -/
theorem integral_fhatRv [IsProbabilityMeasure μ] (X : RandomTriangle Ω n) (f : ℕ → ℝ) (k : ℕ)
    (hM : Mack1 X μ f) (hS : ∀ᵐ ω ∂μ, X.Srv k ω ≠ 0)
    (hCint : ∀ i ∈ contributors n k, Integrable (X.C i (k + 1)) μ)
    (hfint : Integrable (X.fhatRv k) μ) :
    ∫ ω, X.fhatRv k ω ∂μ = f k := by
  have h := condExp_fhatRv X f k hM hS hCint hfint
  rw [← integral_condExp (X.D_le k), integral_congr_ae h]
  simp

end

end VerifiedReserving
