import Mathlib
import VerifiedReserving.ChainLadder

/-!
# Mack's model: the stochastic layer (first theorem)

Mack (1993) works with a random run-off triangle `C i k : Ω → ℝ` and the
σ-algebras `D k` generated by the first `k+1` development years of every
accident year. His first assumption, stated conditionally on the row's own
history and combined with independence across accident years, gives

(M1)  `E[C_{i,k+1} | D_k] = f_k C_{i,k}`   a.s., for every `i` and `k`.

This file states (M1) in exactly that `D_k`-conditioned form and proves the
first half of Mack's Theorem 2: the chain-ladder factor `f̂_k` is
conditionally unbiased, `E[f̂_k | D_k] = f_k`, on the event `S_k ≠ 0`.
The argument is Mack's: `f̂_k = S_k⁻¹ ∑_i C_{i,k+1}`, the factor `S_k⁻¹` is
`D_k`-measurable and comes out of the conditional expectation, and (M1)
turns the remaining sum into `f_k S_k`.

Independence across accident years (M2) is not used here; it is what
justifies passing from Mack's row-conditioned assumption to the
`D_k`-conditioned form, and that passage is a separate lemma to build.
-/

open MeasureTheory Finset Filter

namespace VerifiedReserving

noncomputable section

/-- A random run-off triangle with `n` accident and development years,
together with the filtration `D k` of "everything observed up to development
year `k`". -/
structure RandomTriangle (Ω : Type*) [MeasurableSpace Ω] (n : ℕ) where
  /-- cumulative claims of accident year `i` at development year `k` -/
  C : ℕ → ℕ → Ω → ℝ
  /-- the σ-algebra generated by development years `0, …, k` (all accident years) -/
  D : ℕ → MeasurableSpace Ω
  D_le : ∀ k, D k ≤ ‹MeasurableSpace Ω›
  /-- `C i j` is `D k`-measurable as soon as `j ≤ k` -/
  meas : ∀ i j k, j ≤ k → StronglyMeasurable[D k] (C i j)

variable {Ω : Type*} [MeasurableSpace Ω] {μ : Measure Ω} {n : ℕ}

/-- The pointwise (deterministic) triangle seen at outcome `ω`. -/
def RandomTriangle.at (X : RandomTriangle Ω n) (ω : Ω) : ℕ → ℕ → ℝ :=
  fun i k => X.C i k ω

/-- Mack's first assumption in the `D_k`-conditioned form:
`E[C_{i,k+1} | D_k] = f_k C_{i,k}` almost surely. -/
def Mack1 (X : RandomTriangle Ω n) (μ : Measure Ω) (f : ℕ → ℝ) : Prop :=
  ∀ i k, μ[X.C i (k + 1) | X.D k] =ᵐ[μ] fun ω => f k * X.C i k ω

/-- The column sum `S_k` as a random variable. -/
def RandomTriangle.Srv (X : RandomTriangle Ω n) (k : ℕ) : Ω → ℝ :=
  fun ω => S (X.at ω) n k

/-- The chain-ladder factor `f̂_k` as a random variable. -/
def RandomTriangle.fhatRv (X : RandomTriangle Ω n) (k : ℕ) : Ω → ℝ :=
  fun ω => fhat (X.at ω) n k

theorem RandomTriangle.Srv_eq_sum (X : RandomTriangle Ω n) (k : ℕ) :
    X.Srv k = ∑ i ∈ contributors n k, X.C i k := by
  ext ω
  simp [RandomTriangle.Srv, S, RandomTriangle.at, Finset.sum_apply]

theorem RandomTriangle.fhatRv_eq (X : RandomTriangle Ω n) (k : ℕ) :
    X.fhatRv k = (fun ω => (X.Srv k ω)⁻¹) * ∑ i ∈ contributors n k, X.C i (k + 1) := by
  ext ω
  simp [RandomTriangle.fhatRv, RandomTriangle.Srv, RandomTriangle.at, fhat, T, S,
    Finset.sum_apply, div_eq_inv_mul]

/-- `S_k` is `D_k`-measurable. -/
theorem RandomTriangle.stronglyMeasurable_Srv (X : RandomTriangle Ω n) (k : ℕ) :
    StronglyMeasurable[X.D k] (X.Srv k) := by
  rw [X.Srv_eq_sum]
  exact Finset.stronglyMeasurable_sum _ (fun i _ => X.meas i k k le_rfl)

/-- **Mack (1993), Theorem 2, first part.** Under (M1), on the event
`S_k ≠ 0`, the chain-ladder factor is conditionally unbiased:
`E[f̂_k | D_k] = f_k`. -/
theorem condExp_fhatRv (X : RandomTriangle Ω n) (f : ℕ → ℝ) (k : ℕ)
    (hM : Mack1 X μ f)
    (hS : ∀ᵐ ω ∂μ, X.Srv k ω ≠ 0)
    (hCint : ∀ i ∈ contributors n k, Integrable (X.C i (k + 1)) μ)
    (hfint : Integrable (X.fhatRv k) μ) :
    μ[X.fhatRv k | X.D k] =ᵐ[μ] fun _ => f k := by
  -- the numerator as a random variable
  set Tk : Ω → ℝ := ∑ i ∈ contributors n k, X.C i (k + 1) with hTk
  have hTint : Integrable Tk μ :=
    (integrable_finsetSum _ hCint).congr
      (Eventually.of_forall fun ω => (Finset.sum_apply ω _ _).symm)
  have hinv : StronglyMeasurable[X.D k] (fun ω => (X.Srv k ω)⁻¹) :=
    ((X.stronglyMeasurable_Srv k).measurable.inv).stronglyMeasurable
  have hprod : Integrable ((fun ω => (X.Srv k ω)⁻¹) * Tk) μ := by
    rw [← X.fhatRv_eq]; exact hfint
  -- pull the `D_k`-measurable factor out
  have h1 : μ[X.fhatRv k | X.D k] =ᵐ[μ] (fun ω => (X.Srv k ω)⁻¹) * μ[Tk | X.D k] := by
    rw [X.fhatRv_eq]
    exact condExp_mul_of_stronglyMeasurable_left hinv hprod hTint
  -- (M1) evaluates the conditional expectation of the numerator
  have h2 : μ[Tk | X.D k] =ᵐ[μ] fun ω => f k * X.Srv k ω := by
    have hsum := condExp_finsetSum hCint (m := X.D k)
    have hall : ∀ᵐ ω ∂μ, ∀ i ∈ contributors n k,
        μ[X.C i (k + 1) | X.D k] ω = f k * X.C i k ω := by
      rw [eventually_all_finset]
      intro i _
      exact hM i k
    refine hsum.trans ?_
    filter_upwards [hall] with ω hω
    rw [Finset.sum_apply, Finset.sum_congr rfl (fun i hi => hω i hi), X.Srv_eq_sum,
      Finset.sum_apply, Finset.mul_sum]
  -- assemble
  refine h1.trans ?_
  filter_upwards [h2, hS] with ω hω hSω
  simp only [Pi.mul_apply, hω]
  field_simp

end

end VerifiedReserving
